# This is a code generation for the tuple types
# since the code is highly repetitive, we can generate it
# through this python script.

import sys
import os

# we will generate Tuple1 all the way to Tuple<NUM_TUPLES>
NUM_TUPLES = 20

def main():
  # find the path of the script
  path = os.path.dirname(os.path.realpath(__file__))+ "/tuple_gen.go"

  # open the tuple file
  f = open(path,"w")

  # write the header
  writeHeader(f)

  # write the tuple types
  for i in range(1, NUM_TUPLES+1):
    writeTuple(f, i)

def writeHeader(f):
  f.write("// WARNING: this file is generated by tuple_gen.py, do NOT touch.\n\n")

  # write the package name
  f.write("package tuple\n\n")

  # write the import
  f.write("import (\n")
  f.write("\t\"errors\"\n")
  f.write("\t\"log\"\n")
  f.write("\t\"unsafe\"\n")
  f.write(")\n\n")

def writeTuple(f, n):
  # generic name for the tuple
  tupleGenericName = f"Tuple{n}[{', '.join(f'T{i}' for i in range(1,n+1))}]"

  # write struct
  f.write(f"type Tuple{n}[{', '.join([f'T{i}' for i in range(1,n+1)])} comparable] struct {{\n")
  for i in range(1, n+1):
    f.write(f"\tV{i} T{i}\n")
  f.write("\ttimestamp int64\n")
  f.write("}\n\n")

  # type check
  f.write(f"var _ Tuple = (*Tuple{n}[{', '.join(['any']*n)}])(nil)\n\n")

  # constructor
  f.write(f"func NewTuple{n}[{', '.join(f'T{i}' for i in range(1,n+1))} comparable]({', '.join([f'v{i} T{i}' for i in range(1,n+1)])}) *Tuple{n}[{', '.join(f'T{i}' for i in range(1,n+1))}] {{\n")
  f.write(f"\treturn &{tupleGenericName}{{\n")
  for i in range(1, n+1):
    f.write(f"\t\tV{i}: v{i},\n")
  f.write("\t}\n")
  f.write("}\n\n")

  # GetField() function
  f.write(f"func (t *{tupleGenericName}) GetField(idx int) unsafe.Pointer {{\n")
  f.write("\tswitch idx {\n")
  for i in range(n):
    f.write(f"\tcase {i}:\n")
    f.write(f"\t\treturn unsafe.Pointer(&t.V{i+1})\n")
  f.write("\tdefault:\n")
  f.write("\t\tlog.Fatal(errors.New(\"Tuple index out of range\"))\n")
  f.write("\t}\n")
  f.write("\treturn nil\n")
  f.write("}\n\n")

  # SetField() function
  f.write(f"func (t *{tupleGenericName}) SetField(field int, val any) error {{\n")
  f.write("\tswitch field {\n")
  for i in range(n):
    f.write(f"\tcase {i}:\n")
    f.write(f"\t\tnval, ok := val.(T{i+1})\n")
    f.write(f"\t\tif !ok {{\n")
    f.write(f"\t\t\treturn ErrWrongFieldType\n")
    f.write(f"\t\t}}\n")
    f.write(f"\t\tt.V{i+1} = nval\n")
    f.write(f"\t\treturn nil\n")
  f.write("\tdefault:\n")
  f.write("\t\treturn ErrExtraField\n")
  f.write("\t}\n")
  f.write("}\n\n")

  # GetTimestamp() function
  f.write(f"func (t *{tupleGenericName}) GetTimestamp() int64 {{\n")
  f.write("\treturn t.timestamp\n")
  f.write("}\n\n")

  # SetTimestamp() function
  f.write(f"func (t *{tupleGenericName}) SetTimestamp(ts int64) {{\n")
  f.write("\tt.timestamp = ts\n")
  f.write("}\n\n")

  # New() function
  f.write(f"func (t *{tupleGenericName}) New() Tuple {{\n")
  f.write(f"\treturn &{tupleGenericName}{{}}\n")
  f.write("}\n\n")

  # Copy() function
  f.write(f"func (t *{tupleGenericName}) Copy() Tuple {{\n")
  f.write(f"\treturn &{tupleGenericName}{{\n")
  for i in range(1, n+1):
    f.write(f"\t\tV{i}: t.V{i},\n")
  f.write("\t\ttimestamp: t.timestamp,\n")
  f.write("\t}\n")
  f.write("}\n\n")

  # Equal() function
  f.write(f"func (t *{tupleGenericName}) Equal(other Tuple) bool {{\n")
  f.write(f"\totherTuple, ok := other.(*{tupleGenericName})\n")
  f.write("\tif !ok {\n")
  f.write("\t\treturn false\n")
  f.write("\t}\n")
  for i in range(1, n+1):
    f.write(f"\tif t.V{i} != otherTuple.V{i} {{\n")
    f.write(f"\t\treturn false\n")
    f.write("\t}\n")
  f.write("\treturn true\n")
  f.write("}\n\n")


if __name__ == "__main__":
  main()