// WARNING: this file is generated by tuple_gen.py, do NOT touch.

package tuple

import (
	"errors"
	"log"
	"unsafe"
)

type Tuple1[T1 comparable] struct {
	V1 T1
	timestamp int64
}

var _ Tuple = (*Tuple1[any])(nil)

func NewTuple1[T1 comparable](v1 T1) *Tuple1[T1] {
	return &Tuple1[T1]{
		V1: v1,
	}
}

func (t *Tuple1[T1]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple1[T1]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple1[T1]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple1[T1]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple1[T1]) New() Tuple {
	return &Tuple1[T1]{}
}

func (t *Tuple1[T1]) Copy() Tuple {
	return &Tuple1[T1]{
		V1: t.V1,
		timestamp: t.timestamp,
	}
}

func (t *Tuple1[T1]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple1[T1])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	return true
}

type Tuple2[T1, T2 comparable] struct {
	V1 T1
	V2 T2
	timestamp int64
}

var _ Tuple = (*Tuple2[any, any])(nil)

func NewTuple2[T1, T2 comparable](v1 T1, v2 T2) *Tuple2[T1, T2] {
	return &Tuple2[T1, T2]{
		V1: v1,
		V2: v2,
	}
}

func (t *Tuple2[T1, T2]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple2[T1, T2]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple2[T1, T2]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple2[T1, T2]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple2[T1, T2]) New() Tuple {
	return &Tuple2[T1, T2]{}
}

func (t *Tuple2[T1, T2]) Copy() Tuple {
	return &Tuple2[T1, T2]{
		V1: t.V1,
		V2: t.V2,
		timestamp: t.timestamp,
	}
}

func (t *Tuple2[T1, T2]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple2[T1, T2])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	return true
}

type Tuple3[T1, T2, T3 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	timestamp int64
}

var _ Tuple = (*Tuple3[any, any, any])(nil)

func NewTuple3[T1, T2, T3 comparable](v1 T1, v2 T2, v3 T3) *Tuple3[T1, T2, T3] {
	return &Tuple3[T1, T2, T3]{
		V1: v1,
		V2: v2,
		V3: v3,
	}
}

func (t *Tuple3[T1, T2, T3]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple3[T1, T2, T3]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple3[T1, T2, T3]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple3[T1, T2, T3]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple3[T1, T2, T3]) New() Tuple {
	return &Tuple3[T1, T2, T3]{}
}

func (t *Tuple3[T1, T2, T3]) Copy() Tuple {
	return &Tuple3[T1, T2, T3]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		timestamp: t.timestamp,
	}
}

func (t *Tuple3[T1, T2, T3]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple3[T1, T2, T3])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	return true
}

type Tuple4[T1, T2, T3, T4 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	timestamp int64
}

var _ Tuple = (*Tuple4[any, any, any, any])(nil)

func NewTuple4[T1, T2, T3, T4 comparable](v1 T1, v2 T2, v3 T3, v4 T4) *Tuple4[T1, T2, T3, T4] {
	return &Tuple4[T1, T2, T3, T4]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
	}
}

func (t *Tuple4[T1, T2, T3, T4]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple4[T1, T2, T3, T4]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple4[T1, T2, T3, T4]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple4[T1, T2, T3, T4]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple4[T1, T2, T3, T4]) New() Tuple {
	return &Tuple4[T1, T2, T3, T4]{}
}

func (t *Tuple4[T1, T2, T3, T4]) Copy() Tuple {
	return &Tuple4[T1, T2, T3, T4]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		timestamp: t.timestamp,
	}
}

func (t *Tuple4[T1, T2, T3, T4]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple4[T1, T2, T3, T4])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	return true
}

type Tuple5[T1, T2, T3, T4, T5 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	timestamp int64
}

var _ Tuple = (*Tuple5[any, any, any, any, any])(nil)

func NewTuple5[T1, T2, T3, T4, T5 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5) *Tuple5[T1, T2, T3, T4, T5] {
	return &Tuple5[T1, T2, T3, T4, T5]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple5[T1, T2, T3, T4, T5]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple5[T1, T2, T3, T4, T5]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple5[T1, T2, T3, T4, T5]) New() Tuple {
	return &Tuple5[T1, T2, T3, T4, T5]{}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) Copy() Tuple {
	return &Tuple5[T1, T2, T3, T4, T5]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		timestamp: t.timestamp,
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple5[T1, T2, T3, T4, T5])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	return true
}

type Tuple6[T1, T2, T3, T4, T5, T6 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	timestamp int64
}

var _ Tuple = (*Tuple6[any, any, any, any, any, any])(nil)

func NewTuple6[T1, T2, T3, T4, T5, T6 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6) *Tuple6[T1, T2, T3, T4, T5, T6] {
	return &Tuple6[T1, T2, T3, T4, T5, T6]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) New() Tuple {
	return &Tuple6[T1, T2, T3, T4, T5, T6]{}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Copy() Tuple {
	return &Tuple6[T1, T2, T3, T4, T5, T6]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		timestamp: t.timestamp,
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple6[T1, T2, T3, T4, T5, T6])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	return true
}

type Tuple7[T1, T2, T3, T4, T5, T6, T7 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	timestamp int64
}

var _ Tuple = (*Tuple7[any, any, any, any, any, any, any])(nil)

func NewTuple7[T1, T2, T3, T4, T5, T6, T7 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7) *Tuple7[T1, T2, T3, T4, T5, T6, T7] {
	return &Tuple7[T1, T2, T3, T4, T5, T6, T7]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) New() Tuple {
	return &Tuple7[T1, T2, T3, T4, T5, T6, T7]{}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Copy() Tuple {
	return &Tuple7[T1, T2, T3, T4, T5, T6, T7]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		timestamp: t.timestamp,
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple7[T1, T2, T3, T4, T5, T6, T7])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	return true
}

type Tuple8[T1, T2, T3, T4, T5, T6, T7, T8 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	timestamp int64
}

var _ Tuple = (*Tuple8[any, any, any, any, any, any, any, any])(nil)

func NewTuple8[T1, T2, T3, T4, T5, T6, T7, T8 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8) *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8] {
	return &Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) New() Tuple {
	return &Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]{}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Copy() Tuple {
	return &Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		timestamp: t.timestamp,
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple8[T1, T2, T3, T4, T5, T6, T7, T8])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	return true
}

type Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	timestamp int64
}

var _ Tuple = (*Tuple9[any, any, any, any, any, any, any, any, any])(nil)

func NewTuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9) *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
	return &Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) New() Tuple {
	return &Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Copy() Tuple {
	return &Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		timestamp: t.timestamp,
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	return true
}

type Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	timestamp int64
}

var _ Tuple = (*Tuple10[any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10) *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
	return &Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) New() Tuple {
	return &Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Copy() Tuple {
	return &Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		timestamp: t.timestamp,
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	return true
}

type Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	timestamp int64
}

var _ Tuple = (*Tuple11[any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11) *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] {
	return &Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) New() Tuple {
	return &Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Copy() Tuple {
	return &Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		timestamp: t.timestamp,
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	return true
}

type Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	timestamp int64
}

var _ Tuple = (*Tuple12[any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12) *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return &Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New() Tuple {
	return &Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Copy() Tuple {
	return &Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		timestamp: t.timestamp,
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	return true
}

type Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	timestamp int64
}

var _ Tuple = (*Tuple13[any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13) *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] {
	return &Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
	}
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) New() Tuple {
	return &Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]{}
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) Copy() Tuple {
	return &Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		timestamp: t.timestamp,
	}
}

func (t *Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	return true
}

type Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	timestamp int64
}

var _ Tuple = (*Tuple14[any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14) *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] {
	return &Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
	}
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) New() Tuple {
	return &Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]{}
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) Copy() Tuple {
	return &Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		timestamp: t.timestamp,
	}
}

func (t *Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	return true
}

type Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	timestamp int64
}

var _ Tuple = (*Tuple15[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15) *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] {
	return &Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
	}
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) New() Tuple {
	return &Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]{}
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Copy() Tuple {
	return &Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		timestamp: t.timestamp,
	}
}

func (t *Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	return true
}

type Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	timestamp int64
}

var _ Tuple = (*Tuple16[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15, v16 T16) *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] {
	return &Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
		V16: v16,
	}
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	case 15:
		return unsafe.Pointer(&t.V16)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	case 15:
		nval, ok := val.(T16)
		if !ok {
			return ErrWrongFieldType
		}
		t.V16 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) New() Tuple {
	return &Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]{}
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) Copy() Tuple {
	return &Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		V16: t.V16,
		timestamp: t.timestamp,
	}
}

func (t *Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	if t.V16 != otherTuple.V16 {
		return false
	}
	return true
}

type Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	timestamp int64
}

var _ Tuple = (*Tuple17[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15, v16 T16, v17 T17) *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] {
	return &Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
		V16: v16,
		V17: v17,
	}
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	case 15:
		return unsafe.Pointer(&t.V16)
	case 16:
		return unsafe.Pointer(&t.V17)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	case 15:
		nval, ok := val.(T16)
		if !ok {
			return ErrWrongFieldType
		}
		t.V16 = nval
		return nil
	case 16:
		nval, ok := val.(T17)
		if !ok {
			return ErrWrongFieldType
		}
		t.V17 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) New() Tuple {
	return &Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]{}
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) Copy() Tuple {
	return &Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		V16: t.V16,
		V17: t.V17,
		timestamp: t.timestamp,
	}
}

func (t *Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	if t.V16 != otherTuple.V16 {
		return false
	}
	if t.V17 != otherTuple.V17 {
		return false
	}
	return true
}

type Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	timestamp int64
}

var _ Tuple = (*Tuple18[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15, v16 T16, v17 T17, v18 T18) *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18] {
	return &Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
		V16: v16,
		V17: v17,
		V18: v18,
	}
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	case 15:
		return unsafe.Pointer(&t.V16)
	case 16:
		return unsafe.Pointer(&t.V17)
	case 17:
		return unsafe.Pointer(&t.V18)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	case 15:
		nval, ok := val.(T16)
		if !ok {
			return ErrWrongFieldType
		}
		t.V16 = nval
		return nil
	case 16:
		nval, ok := val.(T17)
		if !ok {
			return ErrWrongFieldType
		}
		t.V17 = nval
		return nil
	case 17:
		nval, ok := val.(T18)
		if !ok {
			return ErrWrongFieldType
		}
		t.V18 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) New() Tuple {
	return &Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]{}
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) Copy() Tuple {
	return &Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		V16: t.V16,
		V17: t.V17,
		V18: t.V18,
		timestamp: t.timestamp,
	}
}

func (t *Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	if t.V16 != otherTuple.V16 {
		return false
	}
	if t.V17 != otherTuple.V17 {
		return false
	}
	if t.V18 != otherTuple.V18 {
		return false
	}
	return true
}

type Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
	timestamp int64
}

var _ Tuple = (*Tuple19[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15, v16 T16, v17 T17, v18 T18, v19 T19) *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19] {
	return &Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
		V16: v16,
		V17: v17,
		V18: v18,
		V19: v19,
	}
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	case 15:
		return unsafe.Pointer(&t.V16)
	case 16:
		return unsafe.Pointer(&t.V17)
	case 17:
		return unsafe.Pointer(&t.V18)
	case 18:
		return unsafe.Pointer(&t.V19)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	case 15:
		nval, ok := val.(T16)
		if !ok {
			return ErrWrongFieldType
		}
		t.V16 = nval
		return nil
	case 16:
		nval, ok := val.(T17)
		if !ok {
			return ErrWrongFieldType
		}
		t.V17 = nval
		return nil
	case 17:
		nval, ok := val.(T18)
		if !ok {
			return ErrWrongFieldType
		}
		t.V18 = nval
		return nil
	case 18:
		nval, ok := val.(T19)
		if !ok {
			return ErrWrongFieldType
		}
		t.V19 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) New() Tuple {
	return &Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]{}
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) Copy() Tuple {
	return &Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		V16: t.V16,
		V17: t.V17,
		V18: t.V18,
		V19: t.V19,
		timestamp: t.timestamp,
	}
}

func (t *Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	if t.V16 != otherTuple.V16 {
		return false
	}
	if t.V17 != otherTuple.V17 {
		return false
	}
	if t.V18 != otherTuple.V18 {
		return false
	}
	if t.V19 != otherTuple.V19 {
		return false
	}
	return true
}

type Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 comparable] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
	V20 T20
	timestamp int64
}

var _ Tuple = (*Tuple20[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any])(nil)

func NewTuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 comparable](v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6, v7 T7, v8 T8, v9 T9, v10 T10, v11 T11, v12 T12, v13 T13, v14 T14, v15 T15, v16 T16, v17 T17, v18 T18, v19 T19, v20 T20) *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20] {
	return &Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]{
		V1: v1,
		V2: v2,
		V3: v3,
		V4: v4,
		V5: v5,
		V6: v6,
		V7: v7,
		V8: v8,
		V9: v9,
		V10: v10,
		V11: v11,
		V12: v12,
		V13: v13,
		V14: v14,
		V15: v15,
		V16: v16,
		V17: v17,
		V18: v18,
		V19: v19,
		V20: v20,
	}
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) GetField(idx int) unsafe.Pointer {
	switch idx {
	case 0:
		return unsafe.Pointer(&t.V1)
	case 1:
		return unsafe.Pointer(&t.V2)
	case 2:
		return unsafe.Pointer(&t.V3)
	case 3:
		return unsafe.Pointer(&t.V4)
	case 4:
		return unsafe.Pointer(&t.V5)
	case 5:
		return unsafe.Pointer(&t.V6)
	case 6:
		return unsafe.Pointer(&t.V7)
	case 7:
		return unsafe.Pointer(&t.V8)
	case 8:
		return unsafe.Pointer(&t.V9)
	case 9:
		return unsafe.Pointer(&t.V10)
	case 10:
		return unsafe.Pointer(&t.V11)
	case 11:
		return unsafe.Pointer(&t.V12)
	case 12:
		return unsafe.Pointer(&t.V13)
	case 13:
		return unsafe.Pointer(&t.V14)
	case 14:
		return unsafe.Pointer(&t.V15)
	case 15:
		return unsafe.Pointer(&t.V16)
	case 16:
		return unsafe.Pointer(&t.V17)
	case 17:
		return unsafe.Pointer(&t.V18)
	case 18:
		return unsafe.Pointer(&t.V19)
	case 19:
		return unsafe.Pointer(&t.V20)
	default:
		log.Fatal(errors.New("Tuple index out of range"))
	}
	return nil
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) SetField(field int, val any) error {
	switch field {
	case 0:
		nval, ok := val.(T1)
		if !ok {
			return ErrWrongFieldType
		}
		t.V1 = nval
		return nil
	case 1:
		nval, ok := val.(T2)
		if !ok {
			return ErrWrongFieldType
		}
		t.V2 = nval
		return nil
	case 2:
		nval, ok := val.(T3)
		if !ok {
			return ErrWrongFieldType
		}
		t.V3 = nval
		return nil
	case 3:
		nval, ok := val.(T4)
		if !ok {
			return ErrWrongFieldType
		}
		t.V4 = nval
		return nil
	case 4:
		nval, ok := val.(T5)
		if !ok {
			return ErrWrongFieldType
		}
		t.V5 = nval
		return nil
	case 5:
		nval, ok := val.(T6)
		if !ok {
			return ErrWrongFieldType
		}
		t.V6 = nval
		return nil
	case 6:
		nval, ok := val.(T7)
		if !ok {
			return ErrWrongFieldType
		}
		t.V7 = nval
		return nil
	case 7:
		nval, ok := val.(T8)
		if !ok {
			return ErrWrongFieldType
		}
		t.V8 = nval
		return nil
	case 8:
		nval, ok := val.(T9)
		if !ok {
			return ErrWrongFieldType
		}
		t.V9 = nval
		return nil
	case 9:
		nval, ok := val.(T10)
		if !ok {
			return ErrWrongFieldType
		}
		t.V10 = nval
		return nil
	case 10:
		nval, ok := val.(T11)
		if !ok {
			return ErrWrongFieldType
		}
		t.V11 = nval
		return nil
	case 11:
		nval, ok := val.(T12)
		if !ok {
			return ErrWrongFieldType
		}
		t.V12 = nval
		return nil
	case 12:
		nval, ok := val.(T13)
		if !ok {
			return ErrWrongFieldType
		}
		t.V13 = nval
		return nil
	case 13:
		nval, ok := val.(T14)
		if !ok {
			return ErrWrongFieldType
		}
		t.V14 = nval
		return nil
	case 14:
		nval, ok := val.(T15)
		if !ok {
			return ErrWrongFieldType
		}
		t.V15 = nval
		return nil
	case 15:
		nval, ok := val.(T16)
		if !ok {
			return ErrWrongFieldType
		}
		t.V16 = nval
		return nil
	case 16:
		nval, ok := val.(T17)
		if !ok {
			return ErrWrongFieldType
		}
		t.V17 = nval
		return nil
	case 17:
		nval, ok := val.(T18)
		if !ok {
			return ErrWrongFieldType
		}
		t.V18 = nval
		return nil
	case 18:
		nval, ok := val.(T19)
		if !ok {
			return ErrWrongFieldType
		}
		t.V19 = nval
		return nil
	case 19:
		nval, ok := val.(T20)
		if !ok {
			return ErrWrongFieldType
		}
		t.V20 = nval
		return nil
	default:
		return ErrExtraField
	}
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) GetTimestamp() int64 {
	return t.timestamp
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) SetTimestamp(ts int64) {
	t.timestamp = ts
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) New() Tuple {
	return &Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]{}
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) Copy() Tuple {
	return &Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]{
		V1: t.V1,
		V2: t.V2,
		V3: t.V3,
		V4: t.V4,
		V5: t.V5,
		V6: t.V6,
		V7: t.V7,
		V8: t.V8,
		V9: t.V9,
		V10: t.V10,
		V11: t.V11,
		V12: t.V12,
		V13: t.V13,
		V14: t.V14,
		V15: t.V15,
		V16: t.V16,
		V17: t.V17,
		V18: t.V18,
		V19: t.V19,
		V20: t.V20,
		timestamp: t.timestamp,
	}
}

func (t *Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) Equal(other Tuple) bool {
	otherTuple, ok := other.(*Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20])
	if !ok {
		return false
	}
	if t.V1 != otherTuple.V1 {
		return false
	}
	if t.V2 != otherTuple.V2 {
		return false
	}
	if t.V3 != otherTuple.V3 {
		return false
	}
	if t.V4 != otherTuple.V4 {
		return false
	}
	if t.V5 != otherTuple.V5 {
		return false
	}
	if t.V6 != otherTuple.V6 {
		return false
	}
	if t.V7 != otherTuple.V7 {
		return false
	}
	if t.V8 != otherTuple.V8 {
		return false
	}
	if t.V9 != otherTuple.V9 {
		return false
	}
	if t.V10 != otherTuple.V10 {
		return false
	}
	if t.V11 != otherTuple.V11 {
		return false
	}
	if t.V12 != otherTuple.V12 {
		return false
	}
	if t.V13 != otherTuple.V13 {
		return false
	}
	if t.V14 != otherTuple.V14 {
		return false
	}
	if t.V15 != otherTuple.V15 {
		return false
	}
	if t.V16 != otherTuple.V16 {
		return false
	}
	if t.V17 != otherTuple.V17 {
		return false
	}
	if t.V18 != otherTuple.V18 {
		return false
	}
	if t.V19 != otherTuple.V19 {
		return false
	}
	if t.V20 != otherTuple.V20 {
		return false
	}
	return true
}

