package buffer

// This is the barrier used by lazy protocol to indicate the end of in-flight
// records: all records after we change the upstream routing has arrived.
// It is generated by the upstream operator and consumed by the old tasks of
// the reconfiguring operator.

type InflightBarrier struct {
}

var _ WorkUnit = (*InflightBarrier)(nil)

func NewInflightBarrier() *InflightBarrier {
	return &InflightBarrier{}
}

// Implement WorkUnit interface
func (i *InflightBarrier) GetType() WorkUnitType {
	return InflightBarrierWorkUnit
}
