// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/grpc/rpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message from Worker to Coordinator
type WorkerToCoordinator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerToCoordinator_RegistrationMsg
	//	*WorkerToCoordinator_ResponseMsg
	Message       isWorkerToCoordinator_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerToCoordinator) Reset() {
	*x = WorkerToCoordinator{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerToCoordinator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToCoordinator) ProtoMessage() {}

func (x *WorkerToCoordinator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToCoordinator.ProtoReflect.Descriptor instead.
func (*WorkerToCoordinator) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerToCoordinator) GetMessage() isWorkerToCoordinator_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerToCoordinator) GetRegistrationMsg() *Registration {
	if x != nil {
		if x, ok := x.Message.(*WorkerToCoordinator_RegistrationMsg); ok {
			return x.RegistrationMsg
		}
	}
	return nil
}

func (x *WorkerToCoordinator) GetResponseMsg() *Response {
	if x != nil {
		if x, ok := x.Message.(*WorkerToCoordinator_ResponseMsg); ok {
			return x.ResponseMsg
		}
	}
	return nil
}

type isWorkerToCoordinator_Message interface {
	isWorkerToCoordinator_Message()
}

type WorkerToCoordinator_RegistrationMsg struct {
	RegistrationMsg *Registration `protobuf:"bytes,1,opt,name=registration_msg,json=registrationMsg,proto3,oneof"`
}

type WorkerToCoordinator_ResponseMsg struct {
	ResponseMsg *Response `protobuf:"bytes,2,opt,name=response_msg,json=responseMsg,proto3,oneof"`
}

func (*WorkerToCoordinator_RegistrationMsg) isWorkerToCoordinator_Message() {}

func (*WorkerToCoordinator_ResponseMsg) isWorkerToCoordinator_Message() {}

// Message from Coordinator to Worker
type CoordinatorToWorker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*CoordinatorToWorker_PauseMsg
	//	*CoordinatorToWorker_RestartMsg
	//	*CoordinatorToWorker_TaskAssignmentMsg
	//	*CoordinatorToWorker_ResponseMsg
	//	*CoordinatorToWorker_StateMigrationMsg
	//	*CoordinatorToWorker_UpdateDownstreamRoutingMsg
	//	*CoordinatorToWorker_RegistrationResponseMsg
	//	*CoordinatorToWorker_StartFastForwardMsg
	//	*CoordinatorToWorker_TerminateMsg
	//	*CoordinatorToWorker_InitLazyReconfigMsg
	//	*CoordinatorToWorker_WaitInboundPeersToConnectMsg
	//	*CoordinatorToWorker_WaitReconfigDoneMsg
	//	*CoordinatorToWorker_PushStateDRRSMsg
	Message       isCoordinatorToWorker_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorToWorker) Reset() {
	*x = CoordinatorToWorker{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorToWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorToWorker) ProtoMessage() {}

func (x *CoordinatorToWorker) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorToWorker.ProtoReflect.Descriptor instead.
func (*CoordinatorToWorker) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorToWorker) GetMessage() isCoordinatorToWorker_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CoordinatorToWorker) GetPauseMsg() *Pause {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_PauseMsg); ok {
			return x.PauseMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetRestartMsg() *Restart {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_RestartMsg); ok {
			return x.RestartMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetTaskAssignmentMsg() *TaskAssignment {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_TaskAssignmentMsg); ok {
			return x.TaskAssignmentMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetResponseMsg() *Response {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_ResponseMsg); ok {
			return x.ResponseMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetStateMigrationMsg() *StateMigration {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_StateMigrationMsg); ok {
			return x.StateMigrationMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetUpdateDownstreamRoutingMsg() *UpdateDownstreamRouting {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_UpdateDownstreamRoutingMsg); ok {
			return x.UpdateDownstreamRoutingMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetRegistrationResponseMsg() *RegistrationResponse {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_RegistrationResponseMsg); ok {
			return x.RegistrationResponseMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetStartFastForwardMsg() *StartFastForward {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_StartFastForwardMsg); ok {
			return x.StartFastForwardMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetTerminateMsg() *Terminate {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_TerminateMsg); ok {
			return x.TerminateMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetInitLazyReconfigMsg() *InitLazyReconfig {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_InitLazyReconfigMsg); ok {
			return x.InitLazyReconfigMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetWaitInboundPeersToConnectMsg() *WaitInboundPeersToConnect {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_WaitInboundPeersToConnectMsg); ok {
			return x.WaitInboundPeersToConnectMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetWaitReconfigDoneMsg() *WaitReconfigDone {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_WaitReconfigDoneMsg); ok {
			return x.WaitReconfigDoneMsg
		}
	}
	return nil
}

func (x *CoordinatorToWorker) GetPushStateDRRSMsg() *StateMigration {
	if x != nil {
		if x, ok := x.Message.(*CoordinatorToWorker_PushStateDRRSMsg); ok {
			return x.PushStateDRRSMsg
		}
	}
	return nil
}

type isCoordinatorToWorker_Message interface {
	isCoordinatorToWorker_Message()
}

type CoordinatorToWorker_PauseMsg struct {
	PauseMsg *Pause `protobuf:"bytes,1,opt,name=pause_msg,json=pauseMsg,proto3,oneof"`
}

type CoordinatorToWorker_RestartMsg struct {
	RestartMsg *Restart `protobuf:"bytes,2,opt,name=restart_msg,json=restartMsg,proto3,oneof"`
}

type CoordinatorToWorker_TaskAssignmentMsg struct {
	TaskAssignmentMsg *TaskAssignment `protobuf:"bytes,3,opt,name=taskAssignment_msg,json=taskAssignmentMsg,proto3,oneof"`
}

type CoordinatorToWorker_ResponseMsg struct {
	ResponseMsg *Response `protobuf:"bytes,4,opt,name=response_msg,json=responseMsg,proto3,oneof"`
}

type CoordinatorToWorker_StateMigrationMsg struct {
	StateMigrationMsg *StateMigration `protobuf:"bytes,5,opt,name=stateMigration_msg,json=stateMigrationMsg,proto3,oneof"`
}

type CoordinatorToWorker_UpdateDownstreamRoutingMsg struct {
	UpdateDownstreamRoutingMsg *UpdateDownstreamRouting `protobuf:"bytes,6,opt,name=updateDownstreamRouting_msg,json=updateDownstreamRoutingMsg,proto3,oneof"`
}

type CoordinatorToWorker_RegistrationResponseMsg struct {
	RegistrationResponseMsg *RegistrationResponse `protobuf:"bytes,7,opt,name=registrationResponse_msg,json=registrationResponseMsg,proto3,oneof"`
}

type CoordinatorToWorker_StartFastForwardMsg struct {
	StartFastForwardMsg *StartFastForward `protobuf:"bytes,8,opt,name=startFastForward_msg,json=startFastForwardMsg,proto3,oneof"`
}

type CoordinatorToWorker_TerminateMsg struct {
	TerminateMsg *Terminate `protobuf:"bytes,9,opt,name=terminate_msg,json=terminateMsg,proto3,oneof"`
}

type CoordinatorToWorker_InitLazyReconfigMsg struct {
	InitLazyReconfigMsg *InitLazyReconfig `protobuf:"bytes,10,opt,name=initLazyReconfig_msg,json=initLazyReconfigMsg,proto3,oneof"`
}

type CoordinatorToWorker_WaitInboundPeersToConnectMsg struct {
	WaitInboundPeersToConnectMsg *WaitInboundPeersToConnect `protobuf:"bytes,11,opt,name=waitInboundPeersToConnect_msg,json=waitInboundPeersToConnectMsg,proto3,oneof"`
}

type CoordinatorToWorker_WaitReconfigDoneMsg struct {
	WaitReconfigDoneMsg *WaitReconfigDone `protobuf:"bytes,12,opt,name=waitReconfigDone_msg,json=waitReconfigDoneMsg,proto3,oneof"`
}

type CoordinatorToWorker_PushStateDRRSMsg struct {
	PushStateDRRSMsg *StateMigration `protobuf:"bytes,13,opt,name=pushStateDRRS_msg,json=pushStateDRRSMsg,proto3,oneof"`
}

func (*CoordinatorToWorker_PauseMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_RestartMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_TaskAssignmentMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_ResponseMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_StateMigrationMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_UpdateDownstreamRoutingMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_RegistrationResponseMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_StartFastForwardMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_TerminateMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_InitLazyReconfigMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_WaitInboundPeersToConnectMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_WaitReconfigDoneMsg) isCoordinatorToWorker_Message() {}

func (*CoordinatorToWorker_PushStateDRRSMsg) isCoordinatorToWorker_Message() {}

type TaskAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task ID - same as Operator ID
	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// Downstream addresses - needed by Collector
	DownstreamInfoList []*DownstreamInfo `protobuf:"bytes,2,rep,name=downstreamInfoList,proto3" json:"downstreamInfoList,omitempty"`
	// Number of expected upstream tasks: used by blocking watermark progress
	// at the task deployment phase
	ExpectedNumUpstream int32 `protobuf:"varint,3,opt,name=expectedNumUpstream,proto3" json:"expectedNumUpstream,omitempty"`
	// Key routing table for keyby collector
	// Only needed if output is a keyed stream
	KeybyCollectorRoutingTable *SerializedKeyLookupTable `protobuf:"bytes,4,opt,name=keybyCollectorRoutingTable,proto3,oneof" json:"keybyCollectorRoutingTable,omitempty"`
	// If the operator is a source operator, provide the source's
	// replica ID
	SourceReplicaId *int64 `protobuf:"varint,5,opt,name=sourceReplicaId,proto3,oneof" json:"sourceReplicaId,omitempty"`
	// [lazy protocol] If lazy protocl is configured and the task is stateful,
	// provide the state lookup table for StateService
	StateLookupTable *SerializedKeyLookupTable `protobuf:"bytes,6,opt,name=stateLookupTable,proto3,oneof" json:"stateLookupTable,omitempty"`
	// [lazy protocol] If lazy protocl is configured and the task is stateful,
	// provide peer state service addresses for remote state access.
	PeerStateService *PeerStateService `protobuf:"bytes,7,opt,name=peerStateService,proto3,oneof" json:"peerStateService,omitempty"`
	// [lazy protocol] Expected number of in-flight barriers to reach alignment
	ExpectedDrainBarriers *int32 `protobuf:"varint,8,opt,name=expectedDrainBarriers,proto3,oneof" json:"expectedDrainBarriers,omitempty"`
	// [lazy protocol] Expected number inbound peer connections
	ExpectedInboundPeers *int32 `protobuf:"varint,9,opt,name=expectedInboundPeers,proto3,oneof" json:"expectedInboundPeers,omitempty"`
	// [DRRS] Not nil if this task is a new task for reconfig. Furthermore,
	// If the info list is not empty, this is a receiver task
	DrrsMigrationInfo *StateMigration `protobuf:"bytes,10,opt,name=drrsMigrationInfo,proto3,oneof" json:"drrsMigrationInfo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetDownstreamInfoList() []*DownstreamInfo {
	if x != nil {
		return x.DownstreamInfoList
	}
	return nil
}

func (x *TaskAssignment) GetExpectedNumUpstream() int32 {
	if x != nil {
		return x.ExpectedNumUpstream
	}
	return 0
}

func (x *TaskAssignment) GetKeybyCollectorRoutingTable() *SerializedKeyLookupTable {
	if x != nil {
		return x.KeybyCollectorRoutingTable
	}
	return nil
}

func (x *TaskAssignment) GetSourceReplicaId() int64 {
	if x != nil && x.SourceReplicaId != nil {
		return *x.SourceReplicaId
	}
	return 0
}

func (x *TaskAssignment) GetStateLookupTable() *SerializedKeyLookupTable {
	if x != nil {
		return x.StateLookupTable
	}
	return nil
}

func (x *TaskAssignment) GetPeerStateService() *PeerStateService {
	if x != nil {
		return x.PeerStateService
	}
	return nil
}

func (x *TaskAssignment) GetExpectedDrainBarriers() int32 {
	if x != nil && x.ExpectedDrainBarriers != nil {
		return *x.ExpectedDrainBarriers
	}
	return 0
}

func (x *TaskAssignment) GetExpectedInboundPeers() int32 {
	if x != nil && x.ExpectedInboundPeers != nil {
		return *x.ExpectedInboundPeers
	}
	return 0
}

func (x *TaskAssignment) GetDrrsMigrationInfo() *StateMigration {
	if x != nil {
		return x.DrrsMigrationInfo
	}
	return nil
}

type InitLazyReconfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expected number of in-flight barriers to reach alignment
	ExpectedDrainBarriers int32 `protobuf:"varint,1,opt,name=expectedDrainBarriers,proto3" json:"expectedDrainBarriers,omitempty"`
	// Expected number inbound peer connections
	ExpectedInboundPeers int32 `protobuf:"varint,2,opt,name=expectedInboundPeers,proto3" json:"expectedInboundPeers,omitempty"`
	// For error checking purposes: notify the task it is shutting down
	IsShuttingDown bool `protobuf:"varint,3,opt,name=isShuttingDown,proto3" json:"isShuttingDown,omitempty"`
	// If new tasks are added during reconfig, we should provide their peer
	// state service addresses for existing tasks - they could be used for
	// multi-reconfiguration scenarios
	PeerStateService *PeerStateService `protobuf:"bytes,4,opt,name=peerStateService,proto3" json:"peerStateService,omitempty"`
	// [DRRS] If the list is not empty, this is a receiver task
	DrrsMigrationInfo *StateMigration `protobuf:"bytes,5,opt,name=drrsMigrationInfo,proto3" json:"drrsMigrationInfo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitLazyReconfig) Reset() {
	*x = InitLazyReconfig{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitLazyReconfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLazyReconfig) ProtoMessage() {}

func (x *InitLazyReconfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLazyReconfig.ProtoReflect.Descriptor instead.
func (*InitLazyReconfig) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *InitLazyReconfig) GetExpectedDrainBarriers() int32 {
	if x != nil {
		return x.ExpectedDrainBarriers
	}
	return 0
}

func (x *InitLazyReconfig) GetExpectedInboundPeers() int32 {
	if x != nil {
		return x.ExpectedInboundPeers
	}
	return 0
}

func (x *InitLazyReconfig) GetIsShuttingDown() bool {
	if x != nil {
		return x.IsShuttingDown
	}
	return false
}

func (x *InitLazyReconfig) GetPeerStateService() *PeerStateService {
	if x != nil {
		return x.PeerStateService
	}
	return nil
}

func (x *InitLazyReconfig) GetDrrsMigrationInfo() *StateMigration {
	if x != nil {
		return x.DrrsMigrationInfo
	}
	return nil
}

type WaitInboundPeersToConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitInboundPeersToConnect) Reset() {
	*x = WaitInboundPeersToConnect{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitInboundPeersToConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitInboundPeersToConnect) ProtoMessage() {}

func (x *WaitInboundPeersToConnect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitInboundPeersToConnect.ProtoReflect.Descriptor instead.
func (*WaitInboundPeersToConnect) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{4}
}

type WaitReconfigDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitReconfigDone) Reset() {
	*x = WaitReconfigDone{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitReconfigDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitReconfigDone) ProtoMessage() {}

func (x *WaitReconfigDone) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitReconfigDone.ProtoReflect.Descriptor instead.
func (*WaitReconfigDone) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{5}
}

type DownstreamInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Downstream WorkerId - uint16 is used but in proto only uint32 is
	// available
	WorkerId uint32 `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	// Downstream data plane address
	DataPlaneAddr string `protobuf:"bytes,2,opt,name=dataPlaneAddr,proto3" json:"dataPlaneAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownstreamInfo) Reset() {
	*x = DownstreamInfo{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownstreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamInfo) ProtoMessage() {}

func (x *DownstreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamInfo.ProtoReflect.Descriptor instead.
func (*DownstreamInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *DownstreamInfo) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *DownstreamInfo) GetDataPlaneAddr() string {
	if x != nil {
		return x.DataPlaneAddr
	}
	return ""
}

type PeerStateService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of addresses for all peer state services
	PeerStateServiceInfoList []*PeerStateServiceInfo `protobuf:"bytes,1,rep,name=peerStateServiceInfoList,proto3" json:"peerStateServiceInfoList,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PeerStateService) Reset() {
	*x = PeerStateService{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStateService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStateService) ProtoMessage() {}

func (x *PeerStateService) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStateService.ProtoReflect.Descriptor instead.
func (*PeerStateService) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *PeerStateService) GetPeerStateServiceInfoList() []*PeerStateServiceInfo {
	if x != nil {
		return x.PeerStateServiceInfoList
	}
	return nil
}

type PeerStateServiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer state service worker ID
	WorkerId uint32 `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	// Peer state service address
	StateServiceAddr string `protobuf:"bytes,2,opt,name=stateServiceAddr,proto3" json:"stateServiceAddr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerStateServiceInfo) Reset() {
	*x = PeerStateServiceInfo{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStateServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStateServiceInfo) ProtoMessage() {}

func (x *PeerStateServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStateServiceInfo.ProtoReflect.Descriptor instead.
func (*PeerStateServiceInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *PeerStateServiceInfo) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *PeerStateServiceInfo) GetStateServiceAddr() string {
	if x != nil {
		return x.StateServiceAddr
	}
	return ""
}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlanePort string                 `protobuf:"bytes,1,opt,name=dataPlanePort,proto3" json:"dataPlanePort,omitempty"`
	StateCommPort string                 `protobuf:"bytes,2,opt,name=stateCommPort,proto3" json:"stateCommPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Registration) GetDataPlanePort() string {
	if x != nil {
		return x.DataPlanePort
	}
	return ""
}

func (x *Registration) GetStateCommPort() string {
	if x != nil {
		return x.StateCommPort
	}
	return ""
}

type RegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// Worker ID assigned by Coordinator
	WorkerId      uint32 `protobuf:"varint,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *RegistrationResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *RegistrationResponse) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *Response) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// Notify Worker to pull state from other Workers
type StateMigration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of migration info: could migrate states from multiple workers
	MigrationInfoList []*MigrationInfo `protobuf:"bytes,1,rep,name=migrationInfoList,proto3" json:"migrationInfoList,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateMigration) Reset() {
	*x = StateMigration{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateMigration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMigration) ProtoMessage() {}

func (x *StateMigration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMigration.ProtoReflect.Descriptor instead.
func (*StateMigration) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *StateMigration) GetMigrationInfoList() []*MigrationInfo {
	if x != nil {
		return x.MigrationInfoList
	}
	return nil
}

// A single migration info: pull what buckets from which worker
type MigrationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target workers to pull state from
	// Each targetWorker is identified as "IP:StateCommPort"
	TargetWorkerAddr string `protobuf:"bytes,1,opt,name=targetWorkerAddr,proto3" json:"targetWorkerAddr,omitempty"`
	// What buckets to pull from targetWorker
	BucketRanges  []*BucketRange `protobuf:"bytes,2,rep,name=bucketRanges,proto3" json:"bucketRanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationInfo) Reset() {
	*x = MigrationInfo{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationInfo) ProtoMessage() {}

func (x *MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationInfo.ProtoReflect.Descriptor instead.
func (*MigrationInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *MigrationInfo) GetTargetWorkerAddr() string {
	if x != nil {
		return x.TargetWorkerAddr
	}
	return ""
}

func (x *MigrationInfo) GetBucketRanges() []*BucketRange {
	if x != nil {
		return x.BucketRanges
	}
	return nil
}

// Message worker to update its downstream routing:
// 1. Add/Remove downstream connections
// 2. Update keyby collector routing table
type UpdateDownstreamRouting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of downstreams to add
	DownstreamsToAdd []*DownstreamInfo `protobuf:"bytes,1,rep,name=downstreamsToAdd,proto3" json:"downstreamsToAdd,omitempty"`
	// List of downstreams to remove
	DownstreamsToRemove []*DownstreamInfo `protobuf:"bytes,2,rep,name=downstreamsToRemove,proto3" json:"downstreamsToRemove,omitempty"`
	// Updated routing table if downstream is stateful operator
	KeybyCollectorRoutingTable *SerializedKeyLookupTable `protobuf:"bytes,3,opt,name=keybyCollectorRoutingTable,proto3,oneof" json:"keybyCollectorRoutingTable,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateDownstreamRouting) Reset() {
	*x = UpdateDownstreamRouting{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDownstreamRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDownstreamRouting) ProtoMessage() {}

func (x *UpdateDownstreamRouting) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDownstreamRouting.ProtoReflect.Descriptor instead.
func (*UpdateDownstreamRouting) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDownstreamRouting) GetDownstreamsToAdd() []*DownstreamInfo {
	if x != nil {
		return x.DownstreamsToAdd
	}
	return nil
}

func (x *UpdateDownstreamRouting) GetDownstreamsToRemove() []*DownstreamInfo {
	if x != nil {
		return x.DownstreamsToRemove
	}
	return nil
}

func (x *UpdateDownstreamRouting) GetKeybyCollectorRoutingTable() *SerializedKeyLookupTable {
	if x != nil {
		return x.KeybyCollectorRoutingTable
	}
	return nil
}

type Terminate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terminate) Reset() {
	*x = Terminate{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminate) ProtoMessage() {}

func (x *Terminate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminate.ProtoReflect.Descriptor instead.
func (*Terminate) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{15}
}

type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{16}
}

type Restart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restart) Reset() {
	*x = Restart{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restart) ProtoMessage() {}

func (x *Restart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restart.ProtoReflect.Descriptor instead.
func (*Restart) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{17}
}

// [Lazy protocol] Notify current workers of the reconfiguring operator to
// update the local routing table and fast forward in-flight records
type StartFastForward struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated routing table
	UpdatedRoutingTable *SerializedKeyLookupTable `protobuf:"bytes,1,opt,name=updatedRoutingTable,proto3" json:"updatedRoutingTable,omitempty"`
	// Info to establish peer connections for fast forward
	PeerInfoList  []*DownstreamInfo `protobuf:"bytes,2,rep,name=PeerInfoList,proto3" json:"PeerInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFastForward) Reset() {
	*x = StartFastForward{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFastForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFastForward) ProtoMessage() {}

func (x *StartFastForward) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFastForward.ProtoReflect.Descriptor instead.
func (*StartFastForward) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *StartFastForward) GetUpdatedRoutingTable() *SerializedKeyLookupTable {
	if x != nil {
		return x.UpdatedRoutingTable
	}
	return nil
}

func (x *StartFastForward) GetPeerInfoList() []*DownstreamInfo {
	if x != nil {
		return x.PeerInfoList
	}
	return nil
}

// [DRRS]
type DRRSReceiverInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Worker ID of the receiver worker
	WorkerId uint32 `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	// Address of the receiver worker's state service
	StateServiceAddr string `protobuf:"bytes,2,opt,name=stateServiceAddr,proto3" json:"stateServiceAddr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DRRSReceiverInfo) Reset() {
	*x = DRRSReceiverInfo{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRRSReceiverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRRSReceiverInfo) ProtoMessage() {}

func (x *DRRSReceiverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRRSReceiverInfo.ProtoReflect.Descriptor instead.
func (*DRRSReceiverInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *DRRSReceiverInfo) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *DRRSReceiverInfo) GetStateServiceAddr() string {
	if x != nil {
		return x.StateServiceAddr
	}
	return ""
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=OperatorId,proto3" json:"OperatorId,omitempty"`
	Metrics       []*MetricData          `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *MetricBatch) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *MetricBatch) GetMetrics() []*MetricData {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    string                 `protobuf:"bytes,1,opt,name=MetricType,proto3" json:"MetricType,omitempty"`
	MetricValue   float64                `protobuf:"fixed64,2,opt,name=MetricValue,proto3" json:"MetricValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricData) Reset() {
	*x = MetricData{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricData) ProtoMessage() {}

func (x *MetricData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricData.ProtoReflect.Descriptor instead.
func (*MetricData) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *MetricData) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *MetricData) GetMetricValue() float64 {
	if x != nil {
		return x.MetricValue
	}
	return 0
}

type MetricCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricCollectionResponse) Reset() {
	*x = MetricCollectionResponse{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricCollectionResponse) ProtoMessage() {}

func (x *MetricCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricCollectionResponse.ProtoReflect.Descriptor instead.
func (*MetricCollectionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *MetricCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// [DRRS] Message that contains all state for a bucket
type BucketState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket ID
	BucketId int64 `protobuf:"varint,1,opt,name=bucketId,proto3" json:"bucketId,omitempty"`
	// [][]byte for list of keys
	Keys [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// [][]byte for list of values
	Values        [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketState) Reset() {
	*x = BucketState{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketState) ProtoMessage() {}

func (x *BucketState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketState.ProtoReflect.Descriptor instead.
func (*BucketState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *BucketState) GetBucketId() int64 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *BucketState) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BucketState) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// [stop-and-restart] Bucket ranges to be pulled from the target worker
type BucketsToBePulled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketRanges  []*BucketRange         `protobuf:"bytes,1,rep,name=bucketRanges,proto3" json:"bucketRanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketsToBePulled) Reset() {
	*x = BucketsToBePulled{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketsToBePulled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketsToBePulled) ProtoMessage() {}

func (x *BucketsToBePulled) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketsToBePulled.ProtoReflect.Descriptor instead.
func (*BucketsToBePulled) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *BucketsToBePulled) GetBucketRanges() []*BucketRange {
	if x != nil {
		return x.BucketRanges
	}
	return nil
}

// Requested state is truncated to smaller chunks for data transfer
type StateChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flag to indicate the end of stream
	EndOfStream bool `protobuf:"varint,1,opt,name=endOfStream,proto3" json:"endOfStream,omitempty"`
	// [][]byte for list of keys
	Keys [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// [][]byte for list of values
	Values        [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChunk) Reset() {
	*x = StateChunk{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChunk) ProtoMessage() {}

func (x *StateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChunk.ProtoReflect.Descriptor instead.
func (*StateChunk) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *StateChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *StateChunk) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *StateChunk) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// [stop-and-restart] In-memory task metadata that needs to be migrated e.g.
// timer, active windows
type TaskMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []byte                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMetadata) Reset() {
	*x = TaskMetadata{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetadata) ProtoMessage() {}

func (x *TaskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetadata.ProtoReflect.Descriptor instead.
func (*TaskMetadata) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *TaskMetadata) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// [lazy-basic] Request for remote bucket migration
type BucketMigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator ID to be fetched
	OperatorId uint32 `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// Worker ID of the source worker
	SourceWorkerId uint32 `protobuf:"varint,2,opt,name=sourceWorkerId,proto3" json:"sourceWorkerId,omitempty"`
	// List of bucket ids to be pulled from the target worker
	BucketIds     []int64 `protobuf:"varint,3,rep,packed,name=bucketIds,proto3" json:"bucketIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketMigrationRequest) Reset() {
	*x = BucketMigrationRequest{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketMigrationRequest) ProtoMessage() {}

func (x *BucketMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketMigrationRequest.ProtoReflect.Descriptor instead.
func (*BucketMigrationRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *BucketMigrationRequest) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *BucketMigrationRequest) GetSourceWorkerId() uint32 {
	if x != nil {
		return x.SourceWorkerId
	}
	return 0
}

func (x *BucketMigrationRequest) GetBucketIds() []int64 {
	if x != nil {
		return x.BucketIds
	}
	return nil
}

// [lazy-no-migration] Remote state read by specific keys
type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator ID to be fetched
	OperatorId uint32 `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// [][]byte for list of requested keys
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *ReadRequest) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ReadRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// [lazy-no-migration] Values for requested keys
type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [][]byte for list of values corresponding to the requested keys
	Values        [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *ReadResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// [lazy-no-migration] Remote state write request (overwrite or merge)
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator ID to be updated
	OperatorId uint32 `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// [][]byte for list of keys
	Keys [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// [][]byte for list of values
	Values        [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *WriteRequest) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *WriteRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *WriteRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// [lazy-no-migration] Remote state delete by specific keys
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator ID to be updated
	OperatorId uint32 `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	// [][]byte for list of keys to be deleted
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteRequest) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *DeleteRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// [lazy-optimized] Request for async remote bucket migration
type AsyncBucketMigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AsyncBucketMigrationRequest_ReadRequest
	//	*AsyncBucketMigrationRequest_BucketMigrationRequest
	Message       isAsyncBucketMigrationRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncBucketMigrationRequest) Reset() {
	*x = AsyncBucketMigrationRequest{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncBucketMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncBucketMigrationRequest) ProtoMessage() {}

func (x *AsyncBucketMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncBucketMigrationRequest.ProtoReflect.Descriptor instead.
func (*AsyncBucketMigrationRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{32}
}

func (x *AsyncBucketMigrationRequest) GetMessage() isAsyncBucketMigrationRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AsyncBucketMigrationRequest) GetReadRequest() *ReadRequest {
	if x != nil {
		if x, ok := x.Message.(*AsyncBucketMigrationRequest_ReadRequest); ok {
			return x.ReadRequest
		}
	}
	return nil
}

func (x *AsyncBucketMigrationRequest) GetBucketMigrationRequest() *BucketMigrationRequest {
	if x != nil {
		if x, ok := x.Message.(*AsyncBucketMigrationRequest_BucketMigrationRequest); ok {
			return x.BucketMigrationRequest
		}
	}
	return nil
}

type isAsyncBucketMigrationRequest_Message interface {
	isAsyncBucketMigrationRequest_Message()
}

type AsyncBucketMigrationRequest_ReadRequest struct {
	// Keys read request
	ReadRequest *ReadRequest `protobuf:"bytes,1,opt,name=readRequest,proto3,oneof"`
}

type AsyncBucketMigrationRequest_BucketMigrationRequest struct {
	// Bucket migration request
	BucketMigrationRequest *BucketMigrationRequest `protobuf:"bytes,2,opt,name=bucketMigrationRequest,proto3,oneof"`
}

func (*AsyncBucketMigrationRequest_ReadRequest) isAsyncBucketMigrationRequest_Message() {}

func (*AsyncBucketMigrationRequest_BucketMigrationRequest) isAsyncBucketMigrationRequest_Message() {}

// [lazy-optimized] Response for async remote bucket migration
type AsyncBucketMigrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AsyncBucketMigrationResponse_ReadResponse
	//	*AsyncBucketMigrationResponse_StateChunk
	Message       isAsyncBucketMigrationResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncBucketMigrationResponse) Reset() {
	*x = AsyncBucketMigrationResponse{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncBucketMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncBucketMigrationResponse) ProtoMessage() {}

func (x *AsyncBucketMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncBucketMigrationResponse.ProtoReflect.Descriptor instead.
func (*AsyncBucketMigrationResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{33}
}

func (x *AsyncBucketMigrationResponse) GetMessage() isAsyncBucketMigrationResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AsyncBucketMigrationResponse) GetReadResponse() *ReadResponse {
	if x != nil {
		if x, ok := x.Message.(*AsyncBucketMigrationResponse_ReadResponse); ok {
			return x.ReadResponse
		}
	}
	return nil
}

func (x *AsyncBucketMigrationResponse) GetStateChunk() *StateChunk {
	if x != nil {
		if x, ok := x.Message.(*AsyncBucketMigrationResponse_StateChunk); ok {
			return x.StateChunk
		}
	}
	return nil
}

type isAsyncBucketMigrationResponse_Message interface {
	isAsyncBucketMigrationResponse_Message()
}

type AsyncBucketMigrationResponse_ReadResponse struct {
	// Values for requested keys
	ReadResponse *ReadResponse `protobuf:"bytes,1,opt,name=readResponse,proto3,oneof"`
}

type AsyncBucketMigrationResponse_StateChunk struct {
	// State chunk for bucket migration
	StateChunk *StateChunk `protobuf:"bytes,2,opt,name=stateChunk,proto3,oneof"`
}

func (*AsyncBucketMigrationResponse_ReadResponse) isAsyncBucketMigrationResponse_Message() {}

func (*AsyncBucketMigrationResponse_StateChunk) isAsyncBucketMigrationResponse_Message() {}

// Range of consecutive buckets that are owned by the same worker
// lower and upper are inclusive [lower, upper]
type BucketRange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WokerId        uint32                 `protobuf:"varint,1,opt,name=wokerId,proto3" json:"wokerId,omitempty"`
	LowerBucketIdx int64                  `protobuf:"varint,2,opt,name=lowerBucketIdx,proto3" json:"lowerBucketIdx,omitempty"`
	UpperBucketIdx int64                  `protobuf:"varint,3,opt,name=upperBucketIdx,proto3" json:"upperBucketIdx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BucketRange) Reset() {
	*x = BucketRange{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketRange) ProtoMessage() {}

func (x *BucketRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketRange.ProtoReflect.Descriptor instead.
func (*BucketRange) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{34}
}

func (x *BucketRange) GetWokerId() uint32 {
	if x != nil {
		return x.WokerId
	}
	return 0
}

func (x *BucketRange) GetLowerBucketIdx() int64 {
	if x != nil {
		return x.LowerBucketIdx
	}
	return 0
}

func (x *BucketRange) GetUpperBucketIdx() int64 {
	if x != nil {
		return x.UpperBucketIdx
	}
	return 0
}

// Serialized key lookup table with list of bucket ranges
type SerializedKeyLookupTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketRanges  []*BucketRange         `protobuf:"bytes,1,rep,name=bucketRanges,proto3" json:"bucketRanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedKeyLookupTable) Reset() {
	*x = SerializedKeyLookupTable{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedKeyLookupTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedKeyLookupTable) ProtoMessage() {}

func (x *SerializedKeyLookupTable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedKeyLookupTable.ProtoReflect.Descriptor instead.
func (*SerializedKeyLookupTable) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{35}
}

func (x *SerializedKeyLookupTable) GetBucketRanges() []*BucketRange {
	if x != nil {
		return x.BucketRanges
	}
	return nil
}

type JobConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobConfig) Reset() {
	*x = JobConfig{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobConfig) ProtoMessage() {}

func (x *JobConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobConfig.ProtoReflect.Descriptor instead.
func (*JobConfig) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{36}
}

type RescaleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of operator to be rescaled
	TargetRescaleOp string `protobuf:"bytes,1,opt,name=targetRescaleOp,proto3" json:"targetRescaleOp,omitempty"`
	// Target parallelism after rescale
	TargetParallelism int64 `protobuf:"varint,2,opt,name=targetParallelism,proto3" json:"targetParallelism,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RescaleConfig) Reset() {
	*x = RescaleConfig{}
	mi := &file_internal_grpc_rpc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescaleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescaleConfig) ProtoMessage() {}

func (x *RescaleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rpc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescaleConfig.ProtoReflect.Descriptor instead.
func (*RescaleConfig) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rpc_proto_rawDescGZIP(), []int{37}
}

func (x *RescaleConfig) GetTargetRescaleOp() string {
	if x != nil {
		return x.TargetRescaleOp
	}
	return ""
}

func (x *RescaleConfig) GetTargetParallelism() int64 {
	if x != nil {
		return x.TargetParallelism
	}
	return 0
}

var File_internal_grpc_rpc_proto protoreflect.FileDescriptor

const file_internal_grpc_rpc_proto_rawDesc = "" +
	"\n" +
	"\x17internal/grpc/rpc.proto\x12\x04grpc\"\x96\x01\n" +
	"\x13WorkerToCoordinator\x12?\n" +
	"\x10registration_msg\x18\x01 \x01(\v2\x12.grpc.RegistrationH\x00R\x0fregistrationMsg\x123\n" +
	"\fresponse_msg\x18\x02 \x01(\v2\x0e.grpc.ResponseH\x00R\vresponseMsgB\t\n" +
	"\amessage\"\xc8\a\n" +
	"\x13CoordinatorToWorker\x12*\n" +
	"\tpause_msg\x18\x01 \x01(\v2\v.grpc.PauseH\x00R\bpauseMsg\x120\n" +
	"\vrestart_msg\x18\x02 \x01(\v2\r.grpc.RestartH\x00R\n" +
	"restartMsg\x12E\n" +
	"\x12taskAssignment_msg\x18\x03 \x01(\v2\x14.grpc.TaskAssignmentH\x00R\x11taskAssignmentMsg\x123\n" +
	"\fresponse_msg\x18\x04 \x01(\v2\x0e.grpc.ResponseH\x00R\vresponseMsg\x12E\n" +
	"\x12stateMigration_msg\x18\x05 \x01(\v2\x14.grpc.StateMigrationH\x00R\x11stateMigrationMsg\x12`\n" +
	"\x1bupdateDownstreamRouting_msg\x18\x06 \x01(\v2\x1d.grpc.UpdateDownstreamRoutingH\x00R\x1aupdateDownstreamRoutingMsg\x12W\n" +
	"\x18registrationResponse_msg\x18\a \x01(\v2\x1a.grpc.RegistrationResponseH\x00R\x17registrationResponseMsg\x12K\n" +
	"\x14startFastForward_msg\x18\b \x01(\v2\x16.grpc.StartFastForwardH\x00R\x13startFastForwardMsg\x126\n" +
	"\rterminate_msg\x18\t \x01(\v2\x0f.grpc.TerminateH\x00R\fterminateMsg\x12K\n" +
	"\x14initLazyReconfig_msg\x18\n" +
	" \x01(\v2\x16.grpc.InitLazyReconfigH\x00R\x13initLazyReconfigMsg\x12f\n" +
	"\x1dwaitInboundPeersToConnect_msg\x18\v \x01(\v2\x1f.grpc.WaitInboundPeersToConnectH\x00R\x1cwaitInboundPeersToConnectMsg\x12K\n" +
	"\x14waitReconfigDone_msg\x18\f \x01(\v2\x16.grpc.WaitReconfigDoneH\x00R\x13waitReconfigDoneMsg\x12C\n" +
	"\x11pushStateDRRS_msg\x18\r \x01(\v2\x14.grpc.StateMigrationH\x00R\x10pushStateDRRSMsgB\t\n" +
	"\amessage\"\xb1\x06\n" +
	"\x0eTaskAssignment\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId\x12D\n" +
	"\x12downstreamInfoList\x18\x02 \x03(\v2\x14.grpc.DownstreamInfoR\x12downstreamInfoList\x120\n" +
	"\x13expectedNumUpstream\x18\x03 \x01(\x05R\x13expectedNumUpstream\x12c\n" +
	"\x1akeybyCollectorRoutingTable\x18\x04 \x01(\v2\x1e.grpc.SerializedKeyLookupTableH\x00R\x1akeybyCollectorRoutingTable\x88\x01\x01\x12-\n" +
	"\x0fsourceReplicaId\x18\x05 \x01(\x03H\x01R\x0fsourceReplicaId\x88\x01\x01\x12O\n" +
	"\x10stateLookupTable\x18\x06 \x01(\v2\x1e.grpc.SerializedKeyLookupTableH\x02R\x10stateLookupTable\x88\x01\x01\x12G\n" +
	"\x10peerStateService\x18\a \x01(\v2\x16.grpc.PeerStateServiceH\x03R\x10peerStateService\x88\x01\x01\x129\n" +
	"\x15expectedDrainBarriers\x18\b \x01(\x05H\x04R\x15expectedDrainBarriers\x88\x01\x01\x127\n" +
	"\x14expectedInboundPeers\x18\t \x01(\x05H\x05R\x14expectedInboundPeers\x88\x01\x01\x12G\n" +
	"\x11drrsMigrationInfo\x18\n" +
	" \x01(\v2\x14.grpc.StateMigrationH\x06R\x11drrsMigrationInfo\x88\x01\x01B\x1d\n" +
	"\x1b_keybyCollectorRoutingTableB\x12\n" +
	"\x10_sourceReplicaIdB\x13\n" +
	"\x11_stateLookupTableB\x13\n" +
	"\x11_peerStateServiceB\x18\n" +
	"\x16_expectedDrainBarriersB\x17\n" +
	"\x15_expectedInboundPeersB\x14\n" +
	"\x12_drrsMigrationInfo\"\xac\x02\n" +
	"\x10InitLazyReconfig\x124\n" +
	"\x15expectedDrainBarriers\x18\x01 \x01(\x05R\x15expectedDrainBarriers\x122\n" +
	"\x14expectedInboundPeers\x18\x02 \x01(\x05R\x14expectedInboundPeers\x12&\n" +
	"\x0eisShuttingDown\x18\x03 \x01(\bR\x0eisShuttingDown\x12B\n" +
	"\x10peerStateService\x18\x04 \x01(\v2\x16.grpc.PeerStateServiceR\x10peerStateService\x12B\n" +
	"\x11drrsMigrationInfo\x18\x05 \x01(\v2\x14.grpc.StateMigrationR\x11drrsMigrationInfo\"\x1b\n" +
	"\x19WaitInboundPeersToConnect\"\x12\n" +
	"\x10WaitReconfigDone\"R\n" +
	"\x0eDownstreamInfo\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\rR\bworkerId\x12$\n" +
	"\rdataPlaneAddr\x18\x02 \x01(\tR\rdataPlaneAddr\"j\n" +
	"\x10PeerStateService\x12V\n" +
	"\x18peerStateServiceInfoList\x18\x01 \x03(\v2\x1a.grpc.PeerStateServiceInfoR\x18peerStateServiceInfoList\"^\n" +
	"\x14PeerStateServiceInfo\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\rR\bworkerId\x12*\n" +
	"\x10stateServiceAddr\x18\x02 \x01(\tR\x10stateServiceAddr\"Z\n" +
	"\fRegistration\x12$\n" +
	"\rdataPlanePort\x18\x01 \x01(\tR\rdataPlanePort\x12$\n" +
	"\rstateCommPort\x18\x02 \x01(\tR\rstateCommPort\"F\n" +
	"\x14RegistrationResponse\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\x12\x1a\n" +
	"\bworkerId\x18\x02 \x01(\rR\bworkerId\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"S\n" +
	"\x0eStateMigration\x12A\n" +
	"\x11migrationInfoList\x18\x01 \x03(\v2\x13.grpc.MigrationInfoR\x11migrationInfoList\"r\n" +
	"\rMigrationInfo\x12*\n" +
	"\x10targetWorkerAddr\x18\x01 \x01(\tR\x10targetWorkerAddr\x125\n" +
	"\fbucketRanges\x18\x02 \x03(\v2\x11.grpc.BucketRangeR\fbucketRanges\"\xa7\x02\n" +
	"\x17UpdateDownstreamRouting\x12@\n" +
	"\x10downstreamsToAdd\x18\x01 \x03(\v2\x14.grpc.DownstreamInfoR\x10downstreamsToAdd\x12F\n" +
	"\x13downstreamsToRemove\x18\x02 \x03(\v2\x14.grpc.DownstreamInfoR\x13downstreamsToRemove\x12c\n" +
	"\x1akeybyCollectorRoutingTable\x18\x03 \x01(\v2\x1e.grpc.SerializedKeyLookupTableH\x00R\x1akeybyCollectorRoutingTable\x88\x01\x01B\x1d\n" +
	"\x1b_keybyCollectorRoutingTable\"\v\n" +
	"\tTerminate\"\a\n" +
	"\x05Pause\"\t\n" +
	"\aRestart\"\x9e\x01\n" +
	"\x10StartFastForward\x12P\n" +
	"\x13updatedRoutingTable\x18\x01 \x01(\v2\x1e.grpc.SerializedKeyLookupTableR\x13updatedRoutingTable\x128\n" +
	"\fPeerInfoList\x18\x02 \x03(\v2\x14.grpc.DownstreamInfoR\fPeerInfoList\"Z\n" +
	"\x10DRRSReceiverInfo\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\rR\bworkerId\x12*\n" +
	"\x10stateServiceAddr\x18\x02 \x01(\tR\x10stateServiceAddr\"Y\n" +
	"\vMetricBatch\x12\x1e\n" +
	"\n" +
	"OperatorId\x18\x01 \x01(\tR\n" +
	"OperatorId\x12*\n" +
	"\ametrics\x18\x02 \x03(\v2\x10.grpc.MetricDataR\ametrics\"N\n" +
	"\n" +
	"MetricData\x12\x1e\n" +
	"\n" +
	"MetricType\x18\x01 \x01(\tR\n" +
	"MetricType\x12 \n" +
	"\vMetricValue\x18\x02 \x01(\x01R\vMetricValue\"4\n" +
	"\x18MetricCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"U\n" +
	"\vBucketState\x12\x1a\n" +
	"\bbucketId\x18\x01 \x01(\x03R\bbucketId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\"J\n" +
	"\x11BucketsToBePulled\x125\n" +
	"\fbucketRanges\x18\x01 \x03(\v2\x11.grpc.BucketRangeR\fbucketRanges\"Z\n" +
	"\n" +
	"StateChunk\x12 \n" +
	"\vendOfStream\x18\x01 \x01(\bR\vendOfStream\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\"*\n" +
	"\fTaskMetadata\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\fR\bmetadata\"~\n" +
	"\x16BucketMigrationRequest\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x01 \x01(\rR\n" +
	"operatorId\x12&\n" +
	"\x0esourceWorkerId\x18\x02 \x01(\rR\x0esourceWorkerId\x12\x1c\n" +
	"\tbucketIds\x18\x03 \x03(\x03R\tbucketIds\"A\n" +
	"\vReadRequest\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x01 \x01(\rR\n" +
	"operatorId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"&\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"Z\n" +
	"\fWriteRequest\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x01 \x01(\rR\n" +
	"operatorId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\"C\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x01 \x01(\rR\n" +
	"operatorId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"\xb7\x01\n" +
	"\x1bAsyncBucketMigrationRequest\x125\n" +
	"\vreadRequest\x18\x01 \x01(\v2\x11.grpc.ReadRequestH\x00R\vreadRequest\x12V\n" +
	"\x16bucketMigrationRequest\x18\x02 \x01(\v2\x1c.grpc.BucketMigrationRequestH\x00R\x16bucketMigrationRequestB\t\n" +
	"\amessage\"\x97\x01\n" +
	"\x1cAsyncBucketMigrationResponse\x128\n" +
	"\freadResponse\x18\x01 \x01(\v2\x12.grpc.ReadResponseH\x00R\freadResponse\x122\n" +
	"\n" +
	"stateChunk\x18\x02 \x01(\v2\x10.grpc.StateChunkH\x00R\n" +
	"stateChunkB\t\n" +
	"\amessage\"w\n" +
	"\vBucketRange\x12\x18\n" +
	"\awokerId\x18\x01 \x01(\rR\awokerId\x12&\n" +
	"\x0elowerBucketIdx\x18\x02 \x01(\x03R\x0elowerBucketIdx\x12&\n" +
	"\x0eupperBucketIdx\x18\x03 \x01(\x03R\x0eupperBucketIdx\"Q\n" +
	"\x18SerializedKeyLookupTable\x125\n" +
	"\fbucketRanges\x18\x01 \x03(\v2\x11.grpc.BucketRangeR\fbucketRanges\"\v\n" +
	"\tJobConfig\"g\n" +
	"\rRescaleConfig\x12(\n" +
	"\x0ftargetRescaleOp\x18\x01 \x01(\tR\x0ftargetRescaleOp\x12,\n" +
	"\x11targetParallelism\x18\x02 \x01(\x03R\x11targetParallelism2i\n" +
	"\x12CooridnatorService\x12S\n" +
	"\x15RegisterToCoordinator\x12\x19.grpc.WorkerToCoordinator\x1a\x19.grpc.CoordinatorToWorker\"\x00(\x010\x012a\n" +
	"\x16MetricCollectorService\x12G\n" +
	"\x0eCollectMetrics\x12\x11.grpc.MetricBatch\x1a\x1e.grpc.MetricCollectionResponse\"\x00(\x012\x84\x05\n" +
	"\x10StateCommService\x12C\n" +
	"\x12PullStatePartition\x12\x17.grpc.BucketsToBePulled\x1a\x10.grpc.StateChunk\"\x000\x01\x12D\n" +
	"\x13MigrateTaskMetadata\x12\x17.grpc.BucketsToBePulled\x1a\x12.grpc.TaskMetadata\"\x00\x12M\n" +
	"\x15RemoteBucketMigration\x12\x1c.grpc.BucketMigrationRequest\x1a\x10.grpc.StateChunk\"\x00(\x010\x01\x129\n" +
	"\n" +
	"RemoteRead\x12\x11.grpc.ReadRequest\x1a\x12.grpc.ReadResponse\"\x00(\x010\x01\x12;\n" +
	"\x0fRemoteOverwrite\x12\x12.grpc.WriteRequest\x1a\x0e.grpc.Response\"\x00(\x010\x01\x127\n" +
	"\vRemoteMerge\x12\x12.grpc.WriteRequest\x1a\x0e.grpc.Response\"\x00(\x010\x01\x129\n" +
	"\fRemoteDelete\x12\x13.grpc.DeleteRequest\x1a\x0e.grpc.Response\"\x00(\x010\x01\x12i\n" +
	"\x1aRemoteAsyncBucketMigration\x12!.grpc.AsyncBucketMigrationRequest\x1a\".grpc.AsyncBucketMigrationResponse\"\x00(\x010\x01\x12?\n" +
	"\x16PushStateMigrationDRRS\x12\x11.grpc.BucketState\x1a\x0e.grpc.Response\"\x00(\x012k\n" +
	"\n" +
	"APIService\x12+\n" +
	"\x06RunJob\x12\x0f.grpc.JobConfig\x1a\x0e.grpc.Response\"\x00\x120\n" +
	"\aRescale\x12\x13.grpc.RescaleConfig\x1a\x0e.grpc.Response\"\x00B0Z.github.com/CASP-Systems-BU/koala/internal/grpcb\x06proto3"

var (
	file_internal_grpc_rpc_proto_rawDescOnce sync.Once
	file_internal_grpc_rpc_proto_rawDescData []byte
)

func file_internal_grpc_rpc_proto_rawDescGZIP() []byte {
	file_internal_grpc_rpc_proto_rawDescOnce.Do(func() {
		file_internal_grpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_rpc_proto_rawDesc), len(file_internal_grpc_rpc_proto_rawDesc)))
	})
	return file_internal_grpc_rpc_proto_rawDescData
}

var file_internal_grpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_internal_grpc_rpc_proto_goTypes = []any{
	(*WorkerToCoordinator)(nil),          // 0: grpc.WorkerToCoordinator
	(*CoordinatorToWorker)(nil),          // 1: grpc.CoordinatorToWorker
	(*TaskAssignment)(nil),               // 2: grpc.TaskAssignment
	(*InitLazyReconfig)(nil),             // 3: grpc.InitLazyReconfig
	(*WaitInboundPeersToConnect)(nil),    // 4: grpc.WaitInboundPeersToConnect
	(*WaitReconfigDone)(nil),             // 5: grpc.WaitReconfigDone
	(*DownstreamInfo)(nil),               // 6: grpc.DownstreamInfo
	(*PeerStateService)(nil),             // 7: grpc.PeerStateService
	(*PeerStateServiceInfo)(nil),         // 8: grpc.PeerStateServiceInfo
	(*Registration)(nil),                 // 9: grpc.Registration
	(*RegistrationResponse)(nil),         // 10: grpc.RegistrationResponse
	(*Response)(nil),                     // 11: grpc.Response
	(*StateMigration)(nil),               // 12: grpc.StateMigration
	(*MigrationInfo)(nil),                // 13: grpc.MigrationInfo
	(*UpdateDownstreamRouting)(nil),      // 14: grpc.UpdateDownstreamRouting
	(*Terminate)(nil),                    // 15: grpc.Terminate
	(*Pause)(nil),                        // 16: grpc.Pause
	(*Restart)(nil),                      // 17: grpc.Restart
	(*StartFastForward)(nil),             // 18: grpc.StartFastForward
	(*DRRSReceiverInfo)(nil),             // 19: grpc.DRRSReceiverInfo
	(*MetricBatch)(nil),                  // 20: grpc.MetricBatch
	(*MetricData)(nil),                   // 21: grpc.MetricData
	(*MetricCollectionResponse)(nil),     // 22: grpc.MetricCollectionResponse
	(*BucketState)(nil),                  // 23: grpc.BucketState
	(*BucketsToBePulled)(nil),            // 24: grpc.BucketsToBePulled
	(*StateChunk)(nil),                   // 25: grpc.StateChunk
	(*TaskMetadata)(nil),                 // 26: grpc.TaskMetadata
	(*BucketMigrationRequest)(nil),       // 27: grpc.BucketMigrationRequest
	(*ReadRequest)(nil),                  // 28: grpc.ReadRequest
	(*ReadResponse)(nil),                 // 29: grpc.ReadResponse
	(*WriteRequest)(nil),                 // 30: grpc.WriteRequest
	(*DeleteRequest)(nil),                // 31: grpc.DeleteRequest
	(*AsyncBucketMigrationRequest)(nil),  // 32: grpc.AsyncBucketMigrationRequest
	(*AsyncBucketMigrationResponse)(nil), // 33: grpc.AsyncBucketMigrationResponse
	(*BucketRange)(nil),                  // 34: grpc.BucketRange
	(*SerializedKeyLookupTable)(nil),     // 35: grpc.SerializedKeyLookupTable
	(*JobConfig)(nil),                    // 36: grpc.JobConfig
	(*RescaleConfig)(nil),                // 37: grpc.RescaleConfig
}
var file_internal_grpc_rpc_proto_depIdxs = []int32{
	9,  // 0: grpc.WorkerToCoordinator.registration_msg:type_name -> grpc.Registration
	11, // 1: grpc.WorkerToCoordinator.response_msg:type_name -> grpc.Response
	16, // 2: grpc.CoordinatorToWorker.pause_msg:type_name -> grpc.Pause
	17, // 3: grpc.CoordinatorToWorker.restart_msg:type_name -> grpc.Restart
	2,  // 4: grpc.CoordinatorToWorker.taskAssignment_msg:type_name -> grpc.TaskAssignment
	11, // 5: grpc.CoordinatorToWorker.response_msg:type_name -> grpc.Response
	12, // 6: grpc.CoordinatorToWorker.stateMigration_msg:type_name -> grpc.StateMigration
	14, // 7: grpc.CoordinatorToWorker.updateDownstreamRouting_msg:type_name -> grpc.UpdateDownstreamRouting
	10, // 8: grpc.CoordinatorToWorker.registrationResponse_msg:type_name -> grpc.RegistrationResponse
	18, // 9: grpc.CoordinatorToWorker.startFastForward_msg:type_name -> grpc.StartFastForward
	15, // 10: grpc.CoordinatorToWorker.terminate_msg:type_name -> grpc.Terminate
	3,  // 11: grpc.CoordinatorToWorker.initLazyReconfig_msg:type_name -> grpc.InitLazyReconfig
	4,  // 12: grpc.CoordinatorToWorker.waitInboundPeersToConnect_msg:type_name -> grpc.WaitInboundPeersToConnect
	5,  // 13: grpc.CoordinatorToWorker.waitReconfigDone_msg:type_name -> grpc.WaitReconfigDone
	12, // 14: grpc.CoordinatorToWorker.pushStateDRRS_msg:type_name -> grpc.StateMigration
	6,  // 15: grpc.TaskAssignment.downstreamInfoList:type_name -> grpc.DownstreamInfo
	35, // 16: grpc.TaskAssignment.keybyCollectorRoutingTable:type_name -> grpc.SerializedKeyLookupTable
	35, // 17: grpc.TaskAssignment.stateLookupTable:type_name -> grpc.SerializedKeyLookupTable
	7,  // 18: grpc.TaskAssignment.peerStateService:type_name -> grpc.PeerStateService
	12, // 19: grpc.TaskAssignment.drrsMigrationInfo:type_name -> grpc.StateMigration
	7,  // 20: grpc.InitLazyReconfig.peerStateService:type_name -> grpc.PeerStateService
	12, // 21: grpc.InitLazyReconfig.drrsMigrationInfo:type_name -> grpc.StateMigration
	8,  // 22: grpc.PeerStateService.peerStateServiceInfoList:type_name -> grpc.PeerStateServiceInfo
	13, // 23: grpc.StateMigration.migrationInfoList:type_name -> grpc.MigrationInfo
	34, // 24: grpc.MigrationInfo.bucketRanges:type_name -> grpc.BucketRange
	6,  // 25: grpc.UpdateDownstreamRouting.downstreamsToAdd:type_name -> grpc.DownstreamInfo
	6,  // 26: grpc.UpdateDownstreamRouting.downstreamsToRemove:type_name -> grpc.DownstreamInfo
	35, // 27: grpc.UpdateDownstreamRouting.keybyCollectorRoutingTable:type_name -> grpc.SerializedKeyLookupTable
	35, // 28: grpc.StartFastForward.updatedRoutingTable:type_name -> grpc.SerializedKeyLookupTable
	6,  // 29: grpc.StartFastForward.PeerInfoList:type_name -> grpc.DownstreamInfo
	21, // 30: grpc.MetricBatch.metrics:type_name -> grpc.MetricData
	34, // 31: grpc.BucketsToBePulled.bucketRanges:type_name -> grpc.BucketRange
	28, // 32: grpc.AsyncBucketMigrationRequest.readRequest:type_name -> grpc.ReadRequest
	27, // 33: grpc.AsyncBucketMigrationRequest.bucketMigrationRequest:type_name -> grpc.BucketMigrationRequest
	29, // 34: grpc.AsyncBucketMigrationResponse.readResponse:type_name -> grpc.ReadResponse
	25, // 35: grpc.AsyncBucketMigrationResponse.stateChunk:type_name -> grpc.StateChunk
	34, // 36: grpc.SerializedKeyLookupTable.bucketRanges:type_name -> grpc.BucketRange
	0,  // 37: grpc.CooridnatorService.RegisterToCoordinator:input_type -> grpc.WorkerToCoordinator
	20, // 38: grpc.MetricCollectorService.CollectMetrics:input_type -> grpc.MetricBatch
	24, // 39: grpc.StateCommService.PullStatePartition:input_type -> grpc.BucketsToBePulled
	24, // 40: grpc.StateCommService.MigrateTaskMetadata:input_type -> grpc.BucketsToBePulled
	27, // 41: grpc.StateCommService.RemoteBucketMigration:input_type -> grpc.BucketMigrationRequest
	28, // 42: grpc.StateCommService.RemoteRead:input_type -> grpc.ReadRequest
	30, // 43: grpc.StateCommService.RemoteOverwrite:input_type -> grpc.WriteRequest
	30, // 44: grpc.StateCommService.RemoteMerge:input_type -> grpc.WriteRequest
	31, // 45: grpc.StateCommService.RemoteDelete:input_type -> grpc.DeleteRequest
	32, // 46: grpc.StateCommService.RemoteAsyncBucketMigration:input_type -> grpc.AsyncBucketMigrationRequest
	23, // 47: grpc.StateCommService.PushStateMigrationDRRS:input_type -> grpc.BucketState
	36, // 48: grpc.APIService.RunJob:input_type -> grpc.JobConfig
	37, // 49: grpc.APIService.Rescale:input_type -> grpc.RescaleConfig
	1,  // 50: grpc.CooridnatorService.RegisterToCoordinator:output_type -> grpc.CoordinatorToWorker
	22, // 51: grpc.MetricCollectorService.CollectMetrics:output_type -> grpc.MetricCollectionResponse
	25, // 52: grpc.StateCommService.PullStatePartition:output_type -> grpc.StateChunk
	26, // 53: grpc.StateCommService.MigrateTaskMetadata:output_type -> grpc.TaskMetadata
	25, // 54: grpc.StateCommService.RemoteBucketMigration:output_type -> grpc.StateChunk
	29, // 55: grpc.StateCommService.RemoteRead:output_type -> grpc.ReadResponse
	11, // 56: grpc.StateCommService.RemoteOverwrite:output_type -> grpc.Response
	11, // 57: grpc.StateCommService.RemoteMerge:output_type -> grpc.Response
	11, // 58: grpc.StateCommService.RemoteDelete:output_type -> grpc.Response
	33, // 59: grpc.StateCommService.RemoteAsyncBucketMigration:output_type -> grpc.AsyncBucketMigrationResponse
	11, // 60: grpc.StateCommService.PushStateMigrationDRRS:output_type -> grpc.Response
	11, // 61: grpc.APIService.RunJob:output_type -> grpc.Response
	11, // 62: grpc.APIService.Rescale:output_type -> grpc.Response
	50, // [50:63] is the sub-list for method output_type
	37, // [37:50] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_internal_grpc_rpc_proto_init() }
func file_internal_grpc_rpc_proto_init() {
	if File_internal_grpc_rpc_proto != nil {
		return
	}
	file_internal_grpc_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerToCoordinator_RegistrationMsg)(nil),
		(*WorkerToCoordinator_ResponseMsg)(nil),
	}
	file_internal_grpc_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorToWorker_PauseMsg)(nil),
		(*CoordinatorToWorker_RestartMsg)(nil),
		(*CoordinatorToWorker_TaskAssignmentMsg)(nil),
		(*CoordinatorToWorker_ResponseMsg)(nil),
		(*CoordinatorToWorker_StateMigrationMsg)(nil),
		(*CoordinatorToWorker_UpdateDownstreamRoutingMsg)(nil),
		(*CoordinatorToWorker_RegistrationResponseMsg)(nil),
		(*CoordinatorToWorker_StartFastForwardMsg)(nil),
		(*CoordinatorToWorker_TerminateMsg)(nil),
		(*CoordinatorToWorker_InitLazyReconfigMsg)(nil),
		(*CoordinatorToWorker_WaitInboundPeersToConnectMsg)(nil),
		(*CoordinatorToWorker_WaitReconfigDoneMsg)(nil),
		(*CoordinatorToWorker_PushStateDRRSMsg)(nil),
	}
	file_internal_grpc_rpc_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_grpc_rpc_proto_msgTypes[14].OneofWrappers = []any{}
	file_internal_grpc_rpc_proto_msgTypes[32].OneofWrappers = []any{
		(*AsyncBucketMigrationRequest_ReadRequest)(nil),
		(*AsyncBucketMigrationRequest_BucketMigrationRequest)(nil),
	}
	file_internal_grpc_rpc_proto_msgTypes[33].OneofWrappers = []any{
		(*AsyncBucketMigrationResponse_ReadResponse)(nil),
		(*AsyncBucketMigrationResponse_StateChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_rpc_proto_rawDesc), len(file_internal_grpc_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_internal_grpc_rpc_proto_goTypes,
		DependencyIndexes: file_internal_grpc_rpc_proto_depIdxs,
		MessageInfos:      file_internal_grpc_rpc_proto_msgTypes,
	}.Build()
	File_internal_grpc_rpc_proto = out.File
	file_internal_grpc_rpc_proto_goTypes = nil
	file_internal_grpc_rpc_proto_depIdxs = nil
}
