// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/grpc/rpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CooridnatorService_RegisterToCoordinator_FullMethodName = "/grpc.CooridnatorService/RegisterToCoordinator"
)

// CooridnatorServiceClient is the client API for CooridnatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CooridnatorServiceClient interface {
	// Bidirectional control plane communication channel
	RegisterToCoordinator(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerToCoordinator, CoordinatorToWorker], error)
}

type cooridnatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCooridnatorServiceClient(cc grpc.ClientConnInterface) CooridnatorServiceClient {
	return &cooridnatorServiceClient{cc}
}

func (c *cooridnatorServiceClient) RegisterToCoordinator(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerToCoordinator, CoordinatorToWorker], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CooridnatorService_ServiceDesc.Streams[0], CooridnatorService_RegisterToCoordinator_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerToCoordinator, CoordinatorToWorker]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CooridnatorService_RegisterToCoordinatorClient = grpc.BidiStreamingClient[WorkerToCoordinator, CoordinatorToWorker]

// CooridnatorServiceServer is the server API for CooridnatorService service.
// All implementations must embed UnimplementedCooridnatorServiceServer
// for forward compatibility.
type CooridnatorServiceServer interface {
	// Bidirectional control plane communication channel
	RegisterToCoordinator(grpc.BidiStreamingServer[WorkerToCoordinator, CoordinatorToWorker]) error
	mustEmbedUnimplementedCooridnatorServiceServer()
}

// UnimplementedCooridnatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCooridnatorServiceServer struct{}

func (UnimplementedCooridnatorServiceServer) RegisterToCoordinator(grpc.BidiStreamingServer[WorkerToCoordinator, CoordinatorToWorker]) error {
	return status.Error(codes.Unimplemented, "method RegisterToCoordinator not implemented")
}
func (UnimplementedCooridnatorServiceServer) mustEmbedUnimplementedCooridnatorServiceServer() {}
func (UnimplementedCooridnatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCooridnatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CooridnatorServiceServer will
// result in compilation errors.
type UnsafeCooridnatorServiceServer interface {
	mustEmbedUnimplementedCooridnatorServiceServer()
}

func RegisterCooridnatorServiceServer(s grpc.ServiceRegistrar, srv CooridnatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCooridnatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CooridnatorService_ServiceDesc, srv)
}

func _CooridnatorService_RegisterToCoordinator_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CooridnatorServiceServer).RegisterToCoordinator(&grpc.GenericServerStream[WorkerToCoordinator, CoordinatorToWorker]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CooridnatorService_RegisterToCoordinatorServer = grpc.BidiStreamingServer[WorkerToCoordinator, CoordinatorToWorker]

// CooridnatorService_ServiceDesc is the grpc.ServiceDesc for CooridnatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CooridnatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.CooridnatorService",
	HandlerType: (*CooridnatorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterToCoordinator",
			Handler:       _CooridnatorService_RegisterToCoordinator_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/rpc.proto",
}

const (
	MetricCollectorService_CollectMetrics_FullMethodName = "/grpc.MetricCollectorService/CollectMetrics"
)

// MetricCollectorServiceClient is the client API for MetricCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricCollectorServiceClient interface {
	// One directional metric collector service communication channel
	CollectMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, MetricCollectionResponse], error)
}

type metricCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricCollectorServiceClient(cc grpc.ClientConnInterface) MetricCollectorServiceClient {
	return &metricCollectorServiceClient{cc}
}

func (c *metricCollectorServiceClient) CollectMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, MetricCollectionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricCollectorService_ServiceDesc.Streams[0], MetricCollectorService_CollectMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricBatch, MetricCollectionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricCollectorService_CollectMetricsClient = grpc.ClientStreamingClient[MetricBatch, MetricCollectionResponse]

// MetricCollectorServiceServer is the server API for MetricCollectorService service.
// All implementations must embed UnimplementedMetricCollectorServiceServer
// for forward compatibility.
type MetricCollectorServiceServer interface {
	// One directional metric collector service communication channel
	CollectMetrics(grpc.ClientStreamingServer[MetricBatch, MetricCollectionResponse]) error
	mustEmbedUnimplementedMetricCollectorServiceServer()
}

// UnimplementedMetricCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricCollectorServiceServer struct{}

func (UnimplementedMetricCollectorServiceServer) CollectMetrics(grpc.ClientStreamingServer[MetricBatch, MetricCollectionResponse]) error {
	return status.Error(codes.Unimplemented, "method CollectMetrics not implemented")
}
func (UnimplementedMetricCollectorServiceServer) mustEmbedUnimplementedMetricCollectorServiceServer() {
}
func (UnimplementedMetricCollectorServiceServer) testEmbeddedByValue() {}

// UnsafeMetricCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricCollectorServiceServer will
// result in compilation errors.
type UnsafeMetricCollectorServiceServer interface {
	mustEmbedUnimplementedMetricCollectorServiceServer()
}

func RegisterMetricCollectorServiceServer(s grpc.ServiceRegistrar, srv MetricCollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricCollectorService_ServiceDesc, srv)
}

func _MetricCollectorService_CollectMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricCollectorServiceServer).CollectMetrics(&grpc.GenericServerStream[MetricBatch, MetricCollectionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricCollectorService_CollectMetricsServer = grpc.ClientStreamingServer[MetricBatch, MetricCollectionResponse]

// MetricCollectorService_ServiceDesc is the grpc.ServiceDesc for MetricCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MetricCollectorService",
	HandlerType: (*MetricCollectorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectMetrics",
			Handler:       _MetricCollectorService_CollectMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/rpc.proto",
}

const (
	StateCommService_PullStatePartition_FullMethodName         = "/grpc.StateCommService/PullStatePartition"
	StateCommService_MigrateTaskMetadata_FullMethodName        = "/grpc.StateCommService/MigrateTaskMetadata"
	StateCommService_RemoteBucketMigration_FullMethodName      = "/grpc.StateCommService/RemoteBucketMigration"
	StateCommService_RemoteRead_FullMethodName                 = "/grpc.StateCommService/RemoteRead"
	StateCommService_RemoteOverwrite_FullMethodName            = "/grpc.StateCommService/RemoteOverwrite"
	StateCommService_RemoteMerge_FullMethodName                = "/grpc.StateCommService/RemoteMerge"
	StateCommService_RemoteDelete_FullMethodName               = "/grpc.StateCommService/RemoteDelete"
	StateCommService_RemoteAsyncBucketMigration_FullMethodName = "/grpc.StateCommService/RemoteAsyncBucketMigration"
	StateCommService_RemoteByKeyMigration_FullMethodName       = "/grpc.StateCommService/RemoteByKeyMigration"
)

// StateCommServiceClient is the client API for StateCommService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateCommServiceClient interface {
	// [stop-and-restart] State migration api exposed by worker
	// The destination worker calls this api to pull state from source worker
	PullStatePartition(ctx context.Context, in *BucketsToBePulled, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateChunk], error)
	// [stop-and-restart] Migrate in-memory task metadata
	MigrateTaskMetadata(ctx context.Context, in *BucketsToBePulled, opts ...grpc.CallOption) (*TaskMetadata, error)
	// [lazy-basic] Bucket-based state migration
	RemoteBucketMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BucketMigrationRequest, StateChunk], error)
	// [lazy-no-migration] Remote state read without migration
	RemoteRead(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReadRequest, ReadResponse], error)
	// [lazy-no-migration] Remote state write (overwrite)
	RemoteOverwrite(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, Response], error)
	// [lazy-no-migration] Remote state write (merge)
	RemoteMerge(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, Response], error)
	// [lazy-no-migration] Remote state delete
	RemoteDelete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeleteRequest, Response], error)
	// [lazy-optimized] Async state migration
	RemoteAsyncBucketMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LazyOptStateRequest, LazyOptStateResponse], error)
	// [lazy-by-key] Per-key based state migration
	RemoteByKeyMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LazyByKeyStateRequest, KeyResponse], error)
}

type stateCommServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateCommServiceClient(cc grpc.ClientConnInterface) StateCommServiceClient {
	return &stateCommServiceClient{cc}
}

func (c *stateCommServiceClient) PullStatePartition(ctx context.Context, in *BucketsToBePulled, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[0], StateCommService_PullStatePartition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BucketsToBePulled, StateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_PullStatePartitionClient = grpc.ServerStreamingClient[StateChunk]

func (c *stateCommServiceClient) MigrateTaskMetadata(ctx context.Context, in *BucketsToBePulled, opts ...grpc.CallOption) (*TaskMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskMetadata)
	err := c.cc.Invoke(ctx, StateCommService_MigrateTaskMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateCommServiceClient) RemoteBucketMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BucketMigrationRequest, StateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[1], StateCommService_RemoteBucketMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BucketMigrationRequest, StateChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteBucketMigrationClient = grpc.BidiStreamingClient[BucketMigrationRequest, StateChunk]

func (c *stateCommServiceClient) RemoteRead(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReadRequest, ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[2], StateCommService_RemoteRead_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteReadClient = grpc.BidiStreamingClient[ReadRequest, ReadResponse]

func (c *stateCommServiceClient) RemoteOverwrite(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[3], StateCommService_RemoteOverwrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteOverwriteClient = grpc.BidiStreamingClient[WriteRequest, Response]

func (c *stateCommServiceClient) RemoteMerge(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[4], StateCommService_RemoteMerge_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteMergeClient = grpc.BidiStreamingClient[WriteRequest, Response]

func (c *stateCommServiceClient) RemoteDelete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeleteRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[5], StateCommService_RemoteDelete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeleteRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteDeleteClient = grpc.BidiStreamingClient[DeleteRequest, Response]

func (c *stateCommServiceClient) RemoteAsyncBucketMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LazyOptStateRequest, LazyOptStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[6], StateCommService_RemoteAsyncBucketMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LazyOptStateRequest, LazyOptStateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteAsyncBucketMigrationClient = grpc.BidiStreamingClient[LazyOptStateRequest, LazyOptStateResponse]

func (c *stateCommServiceClient) RemoteByKeyMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LazyByKeyStateRequest, KeyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateCommService_ServiceDesc.Streams[7], StateCommService_RemoteByKeyMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LazyByKeyStateRequest, KeyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteByKeyMigrationClient = grpc.BidiStreamingClient[LazyByKeyStateRequest, KeyResponse]

// StateCommServiceServer is the server API for StateCommService service.
// All implementations must embed UnimplementedStateCommServiceServer
// for forward compatibility.
type StateCommServiceServer interface {
	// [stop-and-restart] State migration api exposed by worker
	// The destination worker calls this api to pull state from source worker
	PullStatePartition(*BucketsToBePulled, grpc.ServerStreamingServer[StateChunk]) error
	// [stop-and-restart] Migrate in-memory task metadata
	MigrateTaskMetadata(context.Context, *BucketsToBePulled) (*TaskMetadata, error)
	// [lazy-basic] Bucket-based state migration
	RemoteBucketMigration(grpc.BidiStreamingServer[BucketMigrationRequest, StateChunk]) error
	// [lazy-no-migration] Remote state read without migration
	RemoteRead(grpc.BidiStreamingServer[ReadRequest, ReadResponse]) error
	// [lazy-no-migration] Remote state write (overwrite)
	RemoteOverwrite(grpc.BidiStreamingServer[WriteRequest, Response]) error
	// [lazy-no-migration] Remote state write (merge)
	RemoteMerge(grpc.BidiStreamingServer[WriteRequest, Response]) error
	// [lazy-no-migration] Remote state delete
	RemoteDelete(grpc.BidiStreamingServer[DeleteRequest, Response]) error
	// [lazy-optimized] Async state migration
	RemoteAsyncBucketMigration(grpc.BidiStreamingServer[LazyOptStateRequest, LazyOptStateResponse]) error
	// [lazy-by-key] Per-key based state migration
	RemoteByKeyMigration(grpc.BidiStreamingServer[LazyByKeyStateRequest, KeyResponse]) error
	mustEmbedUnimplementedStateCommServiceServer()
}

// UnimplementedStateCommServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateCommServiceServer struct{}

func (UnimplementedStateCommServiceServer) PullStatePartition(*BucketsToBePulled, grpc.ServerStreamingServer[StateChunk]) error {
	return status.Error(codes.Unimplemented, "method PullStatePartition not implemented")
}
func (UnimplementedStateCommServiceServer) MigrateTaskMetadata(context.Context, *BucketsToBePulled) (*TaskMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateTaskMetadata not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteBucketMigration(grpc.BidiStreamingServer[BucketMigrationRequest, StateChunk]) error {
	return status.Error(codes.Unimplemented, "method RemoteBucketMigration not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteRead(grpc.BidiStreamingServer[ReadRequest, ReadResponse]) error {
	return status.Error(codes.Unimplemented, "method RemoteRead not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteOverwrite(grpc.BidiStreamingServer[WriteRequest, Response]) error {
	return status.Error(codes.Unimplemented, "method RemoteOverwrite not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteMerge(grpc.BidiStreamingServer[WriteRequest, Response]) error {
	return status.Error(codes.Unimplemented, "method RemoteMerge not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteDelete(grpc.BidiStreamingServer[DeleteRequest, Response]) error {
	return status.Error(codes.Unimplemented, "method RemoteDelete not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteAsyncBucketMigration(grpc.BidiStreamingServer[LazyOptStateRequest, LazyOptStateResponse]) error {
	return status.Error(codes.Unimplemented, "method RemoteAsyncBucketMigration not implemented")
}
func (UnimplementedStateCommServiceServer) RemoteByKeyMigration(grpc.BidiStreamingServer[LazyByKeyStateRequest, KeyResponse]) error {
	return status.Error(codes.Unimplemented, "method RemoteByKeyMigration not implemented")
}
func (UnimplementedStateCommServiceServer) mustEmbedUnimplementedStateCommServiceServer() {}
func (UnimplementedStateCommServiceServer) testEmbeddedByValue()                          {}

// UnsafeStateCommServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateCommServiceServer will
// result in compilation errors.
type UnsafeStateCommServiceServer interface {
	mustEmbedUnimplementedStateCommServiceServer()
}

func RegisterStateCommServiceServer(s grpc.ServiceRegistrar, srv StateCommServiceServer) {
	// If the following call panics, it indicates UnimplementedStateCommServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateCommService_ServiceDesc, srv)
}

func _StateCommService_PullStatePartition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BucketsToBePulled)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateCommServiceServer).PullStatePartition(m, &grpc.GenericServerStream[BucketsToBePulled, StateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_PullStatePartitionServer = grpc.ServerStreamingServer[StateChunk]

func _StateCommService_MigrateTaskMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketsToBePulled)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateCommServiceServer).MigrateTaskMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateCommService_MigrateTaskMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateCommServiceServer).MigrateTaskMetadata(ctx, req.(*BucketsToBePulled))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateCommService_RemoteBucketMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteBucketMigration(&grpc.GenericServerStream[BucketMigrationRequest, StateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteBucketMigrationServer = grpc.BidiStreamingServer[BucketMigrationRequest, StateChunk]

func _StateCommService_RemoteRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteRead(&grpc.GenericServerStream[ReadRequest, ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteReadServer = grpc.BidiStreamingServer[ReadRequest, ReadResponse]

func _StateCommService_RemoteOverwrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteOverwrite(&grpc.GenericServerStream[WriteRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteOverwriteServer = grpc.BidiStreamingServer[WriteRequest, Response]

func _StateCommService_RemoteMerge_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteMerge(&grpc.GenericServerStream[WriteRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteMergeServer = grpc.BidiStreamingServer[WriteRequest, Response]

func _StateCommService_RemoteDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteDelete(&grpc.GenericServerStream[DeleteRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteDeleteServer = grpc.BidiStreamingServer[DeleteRequest, Response]

func _StateCommService_RemoteAsyncBucketMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteAsyncBucketMigration(&grpc.GenericServerStream[LazyOptStateRequest, LazyOptStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteAsyncBucketMigrationServer = grpc.BidiStreamingServer[LazyOptStateRequest, LazyOptStateResponse]

func _StateCommService_RemoteByKeyMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateCommServiceServer).RemoteByKeyMigration(&grpc.GenericServerStream[LazyByKeyStateRequest, KeyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateCommService_RemoteByKeyMigrationServer = grpc.BidiStreamingServer[LazyByKeyStateRequest, KeyResponse]

// StateCommService_ServiceDesc is the grpc.ServiceDesc for StateCommService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateCommService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.StateCommService",
	HandlerType: (*StateCommServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateTaskMetadata",
			Handler:    _StateCommService_MigrateTaskMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullStatePartition",
			Handler:       _StateCommService_PullStatePartition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RemoteBucketMigration",
			Handler:       _StateCommService_RemoteBucketMigration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteRead",
			Handler:       _StateCommService_RemoteRead_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteOverwrite",
			Handler:       _StateCommService_RemoteOverwrite_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteMerge",
			Handler:       _StateCommService_RemoteMerge_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteDelete",
			Handler:       _StateCommService_RemoteDelete_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteAsyncBucketMigration",
			Handler:       _StateCommService_RemoteAsyncBucketMigration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteByKeyMigration",
			Handler:       _StateCommService_RemoteByKeyMigration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/rpc.proto",
}

const (
	RemotePebbleService_Read_FullMethodName       = "/grpc.RemotePebbleService/Read"
	RemotePebbleService_Write_FullMethodName      = "/grpc.RemotePebbleService/Write"
	RemotePebbleService_Delete_FullMethodName     = "/grpc.RemotePebbleService/Delete"
	RemotePebbleService_RangeQuery_FullMethodName = "/grpc.RemotePebbleService/RangeQuery"
)

// RemotePebbleServiceClient is the client API for RemotePebbleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemotePebbleServiceClient interface {
	// Remote pebble read batch of keys
	Read(ctx context.Context, in *PebbleReadRequest, opts ...grpc.CallOption) (*PebbleReadResponse, error)
	// Remote pebble write (overwrite or merge) keys
	Write(ctx context.Context, in *PebbleWriteRequest, opts ...grpc.CallOption) (*PebbleWriteResponse, error)
	// Remote pebble delete keys
	Delete(ctx context.Context, in *PebbleDeleteRequest, opts ...grpc.CallOption) (*Response, error)
	// Remote pebble range query [lower, upper)
	RangeQuery(ctx context.Context, in *PebbleRangeQueryRequest, opts ...grpc.CallOption) (*PebbleRangeQueryResponse, error)
}

type remotePebbleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemotePebbleServiceClient(cc grpc.ClientConnInterface) RemotePebbleServiceClient {
	return &remotePebbleServiceClient{cc}
}

func (c *remotePebbleServiceClient) Read(ctx context.Context, in *PebbleReadRequest, opts ...grpc.CallOption) (*PebbleReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PebbleReadResponse)
	err := c.cc.Invoke(ctx, RemotePebbleService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePebbleServiceClient) Write(ctx context.Context, in *PebbleWriteRequest, opts ...grpc.CallOption) (*PebbleWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PebbleWriteResponse)
	err := c.cc.Invoke(ctx, RemotePebbleService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePebbleServiceClient) Delete(ctx context.Context, in *PebbleDeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RemotePebbleService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePebbleServiceClient) RangeQuery(ctx context.Context, in *PebbleRangeQueryRequest, opts ...grpc.CallOption) (*PebbleRangeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PebbleRangeQueryResponse)
	err := c.cc.Invoke(ctx, RemotePebbleService_RangeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemotePebbleServiceServer is the server API for RemotePebbleService service.
// All implementations must embed UnimplementedRemotePebbleServiceServer
// for forward compatibility.
type RemotePebbleServiceServer interface {
	// Remote pebble read batch of keys
	Read(context.Context, *PebbleReadRequest) (*PebbleReadResponse, error)
	// Remote pebble write (overwrite or merge) keys
	Write(context.Context, *PebbleWriteRequest) (*PebbleWriteResponse, error)
	// Remote pebble delete keys
	Delete(context.Context, *PebbleDeleteRequest) (*Response, error)
	// Remote pebble range query [lower, upper)
	RangeQuery(context.Context, *PebbleRangeQueryRequest) (*PebbleRangeQueryResponse, error)
	mustEmbedUnimplementedRemotePebbleServiceServer()
}

// UnimplementedRemotePebbleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemotePebbleServiceServer struct{}

func (UnimplementedRemotePebbleServiceServer) Read(context.Context, *PebbleReadRequest) (*PebbleReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRemotePebbleServiceServer) Write(context.Context, *PebbleWriteRequest) (*PebbleWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRemotePebbleServiceServer) Delete(context.Context, *PebbleDeleteRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRemotePebbleServiceServer) RangeQuery(context.Context, *PebbleRangeQueryRequest) (*PebbleRangeQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeQuery not implemented")
}
func (UnimplementedRemotePebbleServiceServer) mustEmbedUnimplementedRemotePebbleServiceServer() {}
func (UnimplementedRemotePebbleServiceServer) testEmbeddedByValue()                             {}

// UnsafeRemotePebbleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemotePebbleServiceServer will
// result in compilation errors.
type UnsafeRemotePebbleServiceServer interface {
	mustEmbedUnimplementedRemotePebbleServiceServer()
}

func RegisterRemotePebbleServiceServer(s grpc.ServiceRegistrar, srv RemotePebbleServiceServer) {
	// If the following call panics, it indicates UnimplementedRemotePebbleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemotePebbleService_ServiceDesc, srv)
}

func _RemotePebbleService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PebbleReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePebbleServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePebbleService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePebbleServiceServer).Read(ctx, req.(*PebbleReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePebbleService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PebbleWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePebbleServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePebbleService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePebbleServiceServer).Write(ctx, req.(*PebbleWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePebbleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PebbleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePebbleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePebbleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePebbleServiceServer).Delete(ctx, req.(*PebbleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePebbleService_RangeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PebbleRangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePebbleServiceServer).RangeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePebbleService_RangeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePebbleServiceServer).RangeQuery(ctx, req.(*PebbleRangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemotePebbleService_ServiceDesc is the grpc.ServiceDesc for RemotePebbleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemotePebbleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.RemotePebbleService",
	HandlerType: (*RemotePebbleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _RemotePebbleService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _RemotePebbleService_Write_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RemotePebbleService_Delete_Handler,
		},
		{
			MethodName: "RangeQuery",
			Handler:    _RemotePebbleService_RangeQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/rpc.proto",
}

const (
	APIService_RunJob_FullMethodName  = "/grpc.APIService/RunJob"
	APIService_Rescale_FullMethodName = "/grpc.APIService/Rescale"
)

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIServiceClient interface {
	// Unary API to submit a job
	RunJob(ctx context.Context, in *JobConfig, opts ...grpc.CallOption) (*Response, error)
	// Unary API to rescale a job
	Rescale(ctx context.Context, in *RescaleConfig, opts ...grpc.CallOption) (*Response, error)
}

type aPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServiceClient(cc grpc.ClientConnInterface) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) RunJob(ctx context.Context, in *JobConfig, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, APIService_RunJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) Rescale(ctx context.Context, in *RescaleConfig, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, APIService_Rescale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
// All implementations must embed UnimplementedAPIServiceServer
// for forward compatibility.
type APIServiceServer interface {
	// Unary API to submit a job
	RunJob(context.Context, *JobConfig) (*Response, error)
	// Unary API to rescale a job
	Rescale(context.Context, *RescaleConfig) (*Response, error)
	mustEmbedUnimplementedAPIServiceServer()
}

// UnimplementedAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServiceServer struct{}

func (UnimplementedAPIServiceServer) RunJob(context.Context, *JobConfig) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RunJob not implemented")
}
func (UnimplementedAPIServiceServer) Rescale(context.Context, *RescaleConfig) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Rescale not implemented")
}
func (UnimplementedAPIServiceServer) mustEmbedUnimplementedAPIServiceServer() {}
func (UnimplementedAPIServiceServer) testEmbeddedByValue()                    {}

// UnsafeAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServiceServer will
// result in compilation errors.
type UnsafeAPIServiceServer interface {
	mustEmbedUnimplementedAPIServiceServer()
}

func RegisterAPIServiceServer(s grpc.ServiceRegistrar, srv APIServiceServer) {
	// If the following call panics, it indicates UnimplementedAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIService_ServiceDesc, srv)
}

func _APIService_RunJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RunJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_RunJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RunJob(ctx, req.(*JobConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_Rescale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescaleConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).Rescale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_Rescale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).Rescale(ctx, req.(*RescaleConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// APIService_ServiceDesc is the grpc.ServiceDesc for APIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunJob",
			Handler:    _APIService_RunJob_Handler,
		},
		{
			MethodName: "Rescale",
			Handler:    _APIService_Rescale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/rpc.proto",
}
