package randGenerator

import (
	"math/rand"

	"github.com/CASP-Systems-BU/koala/api/tuple"
	"github.com/CASP-Systems-BU/koala/query/nexmark/config"
	"github.com/CASP-Systems-BU/koala/query/nexmark/models"
)

type RandGenerator struct {
	// Configuration of this generator
	config *config.NexmarkSourceConfig

	// Number of events generated by this generator
	outputEventNumber int64

	// Extra payload for each event
	extraPayload string

	// Total proportion of 3 kinds of events
	totalProportion int
}

func NewRandGenerator(
	cfg *config.NexmarkSourceConfig,
) *RandGenerator {

	return &RandGenerator{
		config:            cfg,
		outputEventNumber: cfg.OutputEventNumber,
		extraPayload:      string(make([]byte, cfg.ExtraPayloadSize)),
		totalProportion:   cfg.PersonProportion + cfg.AuctionProportion + cfg.BidProportion,
	}
}

// Generate PersonEvent according to replicaID and parallelism
func (g *RandGenerator) NextPerson(
	replicaID int64,
	parallelism int,
	random *rand.Rand,
) (tuple.Tuple, error) {
	// How many PersonEvent is generated by all source tasks
	totalPersonEventGenerated := g.outputEventNumber*int64(
		parallelism,
	) + replicaID

	newEventID := GetEventCountSoFar(
		config.Person,
		g.config.PersonProportion,
		totalPersonEventGenerated,
		g.totalProportion,
		g.config.PersonProportion,
		g.config.AuctionProportion,
	)

	eventTimestamp := getEventTime(newEventID, g.config.InterEventDelay)

	event := NextPerson(newEventID, random, eventTimestamp, g.config)
	event.V8 = g.extraPayload
	g.outputEventNumber++

	return event, nil
}

// Generate AuctionEvent according to replicaID and parallelism
func (g *RandGenerator) NextAuction(
	replicaID int64,
	parallelism int,
	random *rand.Rand,
) (tuple.Tuple, error) {
	// How many AuctionEvent is generated by all source tasks
	totalAuctionEventGenerated := g.outputEventNumber*int64(
		parallelism,
	) + replicaID

	newEventID := GetEventCountSoFar(
		config.Auction,
		g.config.AuctionProportion,
		totalAuctionEventGenerated,
		g.totalProportion,
		g.config.PersonProportion,
		g.config.AuctionProportion,
	)

	eventTimestamp := getEventTime(newEventID, g.config.InterEventDelay)

	event := NextAuction(newEventID, random, eventTimestamp, g.config)
	event.V10 = g.extraPayload
	g.outputEventNumber++

	return event, nil
}

// Generate BidEvent according to replicaID and parallelism
func (g *RandGenerator) NextBid(
	replicaID int64,
	parallelism int,
	random *rand.Rand,
) (tuple.Tuple, error) {
	// How many BidEvent is generated by all source tasks
	totalBidEventGenerated := g.outputEventNumber*int64(parallelism) + replicaID

	newEventID := GetEventCountSoFar(
		config.Bid,
		g.config.BidProportion,
		totalBidEventGenerated,
		g.totalProportion,
		g.config.PersonProportion,
		g.config.AuctionProportion,
	)

	eventTimestamp := getEventTime(newEventID, g.config.InterEventDelay)

	event := NextBid(newEventID, random, eventTimestamp, g.config)
	event.V5 = g.extraPayload
	g.outputEventNumber++

	return event, nil
}

// Generate ClosedAuction according to replicaID and parallelism
func (g *RandGenerator) NextClosedAuction(
	replicaID int64,
	parallelism int,
	random *rand.Rand,
) (tuple.Tuple, error) {

	// How many ClosedAuction is generated by all source tasks
	totalEventGenerated := g.outputEventNumber*int64(parallelism) + replicaID

	newEventID := GetEventCountSoFar(
		config.Auction,
		g.config.BidProportion,
		totalEventGenerated,
		g.totalProportion,
		g.config.PersonProportion,
		g.config.AuctionProportion,
	)

	eventTimestamp := getEventTime(newEventID, g.config.InterEventDelay)
	var event *models.ClosedAuctionEvent
	if g.config.WarmupRun {
		event = NextWarmupClosedAuction(newEventID, random, eventTimestamp, g.config, totalEventGenerated, g.totalProportion)
	} else {
		event = NextClosedAuction(newEventID, random, eventTimestamp, g.config)
	}

	event.V6 = g.extraPayload
	g.outputEventNumber++

	return event, nil
}

// Calculate for each type, where should their eventCount start
func StartBase(
	eventType config.EventType,
	personProportion int,
	auctionProportion int,
) int64 {
	switch eventType {
	case config.Person:
		return 0
	case config.Auction:
		return int64(personProportion)
	default:
		return int64(personProportion + auctionProportion)
	}
}

// Calculate what the current eventID(shared among all 3 kinds of event) is
func GetEventCountSoFar(
	eventType config.EventType,
	eventProportion int,
	eventGenerated int64,
	totalProportion int,
	personProportion int,
	auctionProportion int,
) int64 {
	numRoundGenerated := eventGenerated / int64(eventProportion)
	positionInThisRound := eventGenerated % int64(eventProportion)

	return numRoundGenerated*int64(
		totalProportion,
	) + StartBase(
		eventType,
		personProportion,
		auctionProportion,
	) + positionInThisRound
}
